### ISSUE TITLE
More user-friendly flow of GameView and Install Tab

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#11]
I want to see "Play Game" displayed instead of "Go to Library" in the Game View when the game is installed and the executable file is configured, enabling direct game launch instead of having to then manually search for that game in the library.

**Comment by Yelo420** [comment]
Difficult in the current architecture.
One component would take over the task of another specially designed for it.

**Comment by Alfagun74** [comment]
I insist on this feature.
"Go To Library" is a pain when you have a larger library.

My man, you just need to launch the file in GameVault Exec. What's so hard about it? If it's not, you can still show "Go To Library."

**Comment by Yelo420** [comment]
> 

You mean "Play game"

**Comment by Alfagun74** [comment]
Look ill present you the user flow if youre really doing hard to understand the problem here:

- lets say our user has one fify or one hundred games installed
- the user is in the mood for a rythm/music game
- The user searches for games on his server with the horror genre using the library.
- The user clicks through each games and sees a game he already has installed that he would like to play.
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/889863f9-bf10-464e-874d-a46a1458f451)
User clicks on "Go to 🎮" expecting the game to launch
User lands back in the Installs.
User has to manually search for that game in the list of one hundred games. And Click again to launch the game.

you would make this a lot easier if you just offered "play" for installed games directly on the games page.

**Comment by Yelo420** [comment]
Thanks for the nice explanation

Wouldn't the smarter solution be to go to the installed games tab in "Go to Games", only that the scrollbar automatically scrolls to the game?

Or a search bar in the install tab?

**Comment by Alfagun74** [comment]
First proposed solution would still be 2 unnecessary Clicks

Second Second solution sounds useful per se, but does not solve this problem. as he would then need to search **twice**.

There are many other user flows. For example wanting to launch the temporarily aborted game you played from the community tab. Youll land on the game page and then must look for it in the library again. Its a UX equivalent of a car crash.

**Comment by Yelo420** [comment]
That's right, we really have to think of something

**Comment by Yelo420** [comment]
Im not a UX expert, maybe we should open a thread for the community?

**Comment by KairuByte** [comment]
I have to agree with @Alfagun74 here. The game should be playable directly from the info page. The fact that you can get to the info page from the installed list makes this even more imperative imho.

**Comment by Alfagun74** [comment]
Will be implemented in the process of #201
