### ISSUE TITLE
[BUG] Closing the app from tray tells you that it's still open in tray

### ISSUE THREAD

**Issue by 46620** [Phalcode/gamevault-app#143]
**Describe the bug**
When closing the app from the tray, it gives the popup that it's still running in the tray when it's no longer running there.

**To Reproduce**
1. Close the app from the tray.

**Expected behavior**
It shouldn't give a popup when closing the app fully

**Video**
[Video of bug](https://youtu.be/Sy3jyzRUsDA)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Version: commit 44de1f2fc7deb23183d2634f84840dee160860e8, but happens on older builds too

**Comment by Yelo420** [comment]
@46620
Fixed
