### ISSUE TITLE
Implement a client/local protocol or command-line-interface

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#144]
We’ve discussed this on the discord, but I noticed there isn’t an issue created for it, so I’ll flesh it out here.

A local protocol should be considered for the client. Example: `gv://[action]/[args “/“ separated]`

This would allow client interactions from a url shortcut, or even a web interface.

Example actions:
- install a game
- launch a game
- one click connection between backend and client (with client side confirmation of course)
- uninstall a game

Game interactions *would* require a predictable identification for the game, similar to steams implementation.

**Comment by Alfagun74** [comment]
Related: https://github.com/Phalcode/gamevault-backend/issues/9#issuecomment-1626042496

**Comment by Zallist** [comment]
Pull request #360 implements a command line interface, custom uri schema and the ability to send messages directly through the Named Pipe.

**Comment by Alfagun74** [comment]
Open To Dos:
 
- [ ] Test all endpoints manually
- [ ] Implement Paywall
- [ ] Document All Endpoints and their Usage
