### ISSUE TITLE
Client-Side Bandwidth limits

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#153]
**Is your feature request related to a problem? Please describe.**
Similar to any other app that downloads large amounts of data, the client should not always have free rein of all bandwidth available to it. Even if the server side is fine giving out 1gbps, the user may only want the client to use 50mbps because of other network traffic. 

**Describe the solution you'd like**
Add bandwidth limit options.

**Additional context**
Similar to Phalcode/gamevault-backend#10 but on the client side.

**Comment by Alfagun74** [comment]
Mind providing more details what exactly you want in the client? Please use the issue template.

**Comment by KairuByte** [comment]
Edited. Apologies, didn’t think it needed a comprehensive explanation.

**Comment by Alfagun74** [comment]
Got it, I understand now. Initially, I thought you wanted to regulate the serverside bandwidth from the client side, and I was a bit puzzled about what you meant exactly. However, I really like this idea. When I was a teenager, my mother would get upset whenever I downloaded large games while she's trying to watch something on youtube. I'll definitely make sure to save you all from that. Haha!

**Comment by Wh1t3Rose** [comment]
I think we should also have this serverside as an admin. For those of us sharing with multiple clients, we should be able to control how much bandwidth is allowed to be used by clients from the serverside

**Comment by Alfagun74** [comment]
@Wh1t3Rose See https://github.com/Phalcode/gamevault-backend/issues/10

**Comment by Alfagun74** [comment]
I believe the simplest approach to address this, now that https://github.com/Phalcode/gamevault-backend/issues/10 has been completed, is to include a header in the client's download request, such as `throttle_kbps = 5000`. The server will then honor this value and deliver data at that rate. Naturally, it will also verify if this value exceeds the global speed limit and, if it does, limit it accordingly.

**Comment by Alfagun74** [comment]
Implemented in Backend:


![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/4f7a018a-1990-4a35-b9df-fbcab9e701c5)

**Comment by Yelo420** [comment]
Implemented in Client
