### ISSUE TITLE
Make the app realy cross platform by migrating wpf to AvaloniaUI

### ISSUE THREAD

**Issue by yodatak** [Phalcode/gamevault-app#155]
I cannot debug error from my linux because i cannot compile it do i search and discover that wpf windows does not support cross platform as opposed as .net core./

It could be interesting to migrate to avaloniaui that is cross platform and verry close to wpf ( use by unity and many more)
It could permit to have it on android linux steam deck windows mac by exemple 
https://docs.avaloniaui.net/docs/next/get-started/wpf/

I think its the time to make some good fondations for the future 

https://github.com/dotnet/wpf/issues/688
https://github.com/dotnet/wpf/issues/48

https://github.com/AvaloniaCommunity/awesome-avalonia

**Comment by Yelo420** [comment]
Thanks for the feedback.
Yes, the WPF frontend framework unfortunately does not support linux.

Avalonia or maybe even .NET MAUI would be a good alternative for this.

Unfortunately we don't have the time and manpower to migrate the program in its current size to one of the platforms.

However, we plan to do so in the future.

Maybe even with the help of some contributors from the community.

**Comment by teambvd** [comment]
I primarily game on Linux these days, partly out of spite (Microsoft), and often with emulators. Having the ability to install the client on a Linux system would be huge, and Android would be a significant bonus as it has a wealth of support for emulation, and often on less expensive devices.

It'd save from having to effectively run two separate server platforms for gaming, one for PC, one for emulation.

Understanding this is a *MASSIVE* lift, I'm sure it's more work than can be justified at current - I just wanted to add my voice to the request.

Thanks to both you and your partner for bringing this awesome platform to the masses!

**Comment by Alfagun74** [comment]
@teambvd I hope you know there is at least this community based Linux approach working right now: https://gamevau.lt/docs/advanced-usage/linux-client

**Comment by Alfagun74** [comment]
We could also consider rebuilding the app in Flutter, Tauri or Electron in the future.

**Comment by Alfagun74** [comment]
.NET MAUI is the biggest lie. Maui doesn't support Linux desktop, wasn't even built considering it and Microsoft engineers have specifically acknowledged this and so far there are no plan to support Linux desktop: https://github.com/dotnet/maui/discussions/339
