### ISSUE TITLE
Long game titles results in unreadable text

### ISSUE THREAD

**Issue by lenaxia** [Phalcode/gamevault-app#163]
**Describe the bug**
When long game titles exist, the displayed title upon mouseover is so tiny as to be nearly unreadable. 

**To Reproduce**
1. Create a game with a long title
2. mouse over it in the UI

**Expected behavior**
Clearly readable text

**Screenshots**

![image](https://github.com/Phalcode/gamevault-app/assets/6321838/69d5d550-2ce0-44e9-bc5a-4de5e85b15d4)

I suggest an overlay similar to either steam or what is seen on ani-chart (https://anichart.net/). This allows a more consistent control over the meta information formatting.

**Comment by Alfagun74** [comment]
Animated Scrolling Test would also be an option

**Comment by Yelo420** [comment]
Fixed in the next version.
