### ISSUE TITLE
Display estimated install size

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#164]
**Is your feature request related to a problem? Please describe.**
GV currently shows the total download size of the archive, but this is semi deceptive. The archive is going to inherently be smaller than the final extracted size of the installed game. 

**Describe the solution you'd like**
Live Play games should be possible to display the final extracted disk size, and some installers can be checked for the final install size. Where possible this should be visible in the UI.

**Describe alternatives you've considered**
The only real alternative is to just not show the total size on disk.

**Comment by Alfagun74** [comment]
How exactly would you technically solve it for setup games?

**Comment by Alfagun74** [comment]
Determining the exact required game size is challenging to implement. The tools for downloading and extracting files already verify your computer's available space. After some talk, we're leaning towards investing our time in different matters.
