### ISSUE TITLE
Download progress on Windows taskbar button

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#167]
**Is your feature request related to a problem? Please describe.**
Download progress is impossible to see at all unless you click into the application.

**Describe the solution you'd like**
Windows has a feature for hooking into the "taskbar button" of an application, which allows you to show progress of things. Downloads should show progress here for quick and easy estimation of progress without having to click into the UI.

**Comment by Alfagun74** [comment]
Can you maybe give us a visual example of another program that performs this so that we can fully understand what you mean?

**Comment by KairuByte** [comment]
Certainly, this is Google Chrome downloading a file:
![image](https://github.com/Phalcode/gamevault-app/assets/393806/2f2367a6-1f7e-4112-a939-378d18c15009)

**Comment by Alfagun74** [comment]
i like this. @Yelo420 how about you?

**Comment by Yelo420** [comment]
Implemented. Works even with multiple downloads running at the same time by calculating the average
