### ISSUE TITLE
Smaller window causes overflow on download tab (sometimes)

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#168]
**Describe the bug**
Smaller window causes overflow on donwload tab

**Expected behavior**
The open folder and delete options should be on the right side of the window, instead of overflowed the width of the screen.

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/393806/c940d27f-38f8-4218-86d5-78727052a9a7)

**Additional context**
I cant tell if this is a hard coded value, or if the width of the list element is scaling to my screen width, but it should be scaling to the window width instead.

**Comment by Alfagun74** [comment]
What is your resolution.

**Comment by KairuByte** [comment]
Resolution on this monitor is 1920x1080. No idea what the size of the window in that screenshot is though. Might be 1133 x 626?

**Comment by Alfagun74** [comment]
@Yelo420 can you reproduce it? because i cant even with the smallest possible window sizing:

![image](https://github.com/Phalcode/gamevault-app/assets/22225051/b8fc6a63-c4d4-4a48-bed6-66ed7bdd518b)

**Comment by Alfagun74** [comment]
can reproduce it in installs though:
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/25dcb765-a94c-4adb-9563-ded630207cb6)

**Comment by KairuByte** [comment]
This may be a fringe case. After two restarts of the app things have resolved. If I find a way to reproduce reliably I'll add it.

**Comment by Alfagun74** [comment]
Perhaps just Microsoft antics. Please reopen with instructions on how to reproduce if necessary.
