### ISSUE TITLE
Custom Tags

### ISSUE THREAD

**Issue by JamesDAdams** [Phalcode/gamevault-app#172]
**Is your feature request related to a problem? Please describe.**
I want to add custom tag to games for improve research

**Describe the solution you'd like**
Add in edition a new field tag 
![image](https://github.com/Phalcode/gamevault-app/assets/20860324/bddafe58-d515-48a1-9a80-914b67451db1)

Ex : I want to have a tag WINDOWS_GAMES and APK_GAMES

**Describe alternatives you've considered**
I don't have an alternatives

**Additional context**

**Comment by Alfagun74** [comment]
We can utilize the tags and genre implementation we already have and create a post and delete API for custom ones with no connection to rawg. Additionally, we'll require an API for updating games to allow manual addition and removal of tags and genres.

**Comment by Kudjo-Grand** [comment]
I would LOVE to use custom tags! Although, the first thing I would use them for is tagging similar to: "verified", "tested", "ready" on titles that I've ensured are packaged properly and are ready to go. Then I know where to focus future efforts.

**Comment by Alfagun74** [comment]
You could use them however you like, just know every user on the server could potentially see the tags

**Comment by Alfagun74** [comment]
**Probably** needs https://github.com/Phalcode/gamevault-backend/issues/258 first for a better seperation of tags.

**Comment by Alfagun74** [comment]
Also needs https://github.com/Phalcode/gamevault-backend/issues/171

**Comment by Alfagun74** [comment]
Implemented on serverside

**Comment by Alfagun74** [comment]
will be completed via https://github.com/Phalcode/gamevault-backend/issues/161
