### ISSUE TITLE
Remove "Register" and "Log in" sections from the settings

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#174]
**Is your feature request related to a problem? Please describe.**
A logged in user has no use for the ability to either log in, or register... Assuming there is a different way to create a new account for a different user, such as a web UI (see Additional context below.)

**Describe the solution you'd like**
Remove these two sections.

**Additional context**
Dependent on Phalcode/gamevault-backend#150 and potentially Phalcode/gamevault-backend#147.

**Comment by Alfagun74** [comment]
Thank you for your request and for taking the time to share your thoughts with us. We appreciate your input. However, after careful consideration, we have decided to keep the ability to log in and register even with a Web UI in the future for the following reasons:

- Logging In: Some Users often need to log out and log back in for various reasons, such as switching accounts. The option to log in is crucial to maintain a seamless user experience.

- Registering: Allowing users to register for others or for creating multiple accounts can be a legitimate use case. For instance, users may want to create accounts for family members or friends using their own devices. Restricting this functionality could hinder the user experience.

If you have any more suggestions or questions, please feel free to reach out. We value your feedback and are here to help.
