### ISSUE TITLE
Add "Servers & Accounts" section to the settings page

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#175]
**Is your feature request related to a problem? Please describe.**
While users are unable to alter their profile information, it is in an unexpected area. There also does not appear to be a way to sign out?

**Describe the solution you'd like**
Settings such as password, username and email should be within the settings section, under an entry for the specific server the account is associated with. Additionally, a sign out (or "remove server") option should likely be added here. Things meant for the community (Name, images) seem to fit fine where they are (assuming there is a way to change your server here later.)

The "Startup" sections "server url" should likely be removed as well, in favor of setting a default server within the new tab described above.

**Comment by Alfagun74** [comment]
Is this still relevant?

mind of #220 too

**Comment by KairuByte** [comment]
Short term I suppose this could be dropped, but it's going to come up again when multi backend support comes along.
