### ISSUE TITLE
Add the ability to perform a force re-index from the client

### ISSUE THREAD

**Issue by moutonnoireu** [Phalcode/gamevault-app#176]
I would love to get the ability to perform a manual re-index directly from the client. 
- [x] Implement force Reindex Button somewhere in the Admin UI (maybe Sidebar? Tabs? idk.)

**Comment by Alfagun74** [comment]
Could be integrated in the Admin UI, Same goes for force-recache and other util APIs. Just plain buttons to trigger those apis would suffice.

![image](https://github.com/Phalcode/gamevault-app/assets/22225051/deb71169-ee6e-48c8-b812-640a3af8b8fc)

**Comment by Alfagun74** [comment]
Created #219 for the Recache Aspect

**Comment by Yelo420** [comment]
Implemented
