### ISSUE TITLE
Linux Native Client (SteamDeck)

### ISSUE THREAD

**Issue by Ronald-Diemicke** [Phalcode/gamevault-app#177]
**Is your feature request related to a problem? Please describe.**
So - while it seems possible to run this over wine, I'd suggest making sure a multiplatform approach for the client is in the pipeline before you get TOO far... This could be incredible for the steamdeck.

**Describe the solution you'd like**
Would love to see a native linux client (supported through flatpak)

**Describe alternatives you've considered**
First class support for photon/linux and a controller interface for the steamdeck would probably get folks by...

**Comment by Ronald-Diemicke** [comment]
So looking at the project a bit deeper - it seems the client is in C# ... wonder if you could use mono to get this working in Linux?

**Comment by Alfagun74** [comment]
duplicate of https://github.com/Phalcode/gamevault-app/issues/17

**Comment by Alfagun74** [comment]
also .NET 6 runs on every platform by now. Mono is not needed at all. But the problem is that WPF, our UI Framework only works on Windows natively.
