### ISSUE TITLE
Open Error Log

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#181]
**Is your feature request connected to an issue? Please explain.**
Users receive a request to examine or send us the error log, but it's deeply buried. We require a button for swiftly accessing the error log when errors occur.

**Explain the solution you want**
The Error Notification should present a button to view the error log.

**Discuss other options you've thought about**
Include a button to open the folder in the settings.

**Comment by Yelo420** [comment]
The message box now gives you the option to navigate to the error log folder

**Comment by Alfagun74** [comment]
awesome gj
