### ISSUE TITLE
The server/client must be able to handle updates in the form of patches

### ISSUE THREAD

**Issue by joggs** [Phalcode/gamevault-app#184]
**Is your feature request related to a problem? Please describe.**
For almost all games, there are updates that comes in the form of patches rather than a new version of the full game and this must be handled by the server/client

**Describe the solution you'd like**
If you have minecraft 1.20 on the game vault server, and there is an update patch for 1.21, you should be able to put that patch on the server with the same file name as the main game version, but with another version number, and the server should then recognize this and send both files to the client or possible merge the patch into the main file 7z (or what format you are using)

**Describe alternatives you've considered**
The alternative is to not use gamevault until this is implemtented as a samba share would be simpler.

**Additional context**

**Comment by Alfagun74** [comment]
Wow, what a creative alternative solution to the problem. 

You may handle those patches as Mods in the future as described in the planned ticket https://github.com/Phalcode/gamevault-backend/issues/142. Have fun using Samba Shares until then.
