### ISSUE TITLE
Keypress -> Enter on account login page should submit login information

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#185]
**Describe the bug**
Pressing enter on the account login page should submit login information

**To Reproduce**
1. Go to Settings
2. Click on Login
3. Enter login information
4. Hit enter

**Expected behavior**
Login information is submitted, as if the login button had been clicked.

**Comment by Alfagun74** [comment]
Is this Issue only about the missing Keypress -> Enter?

**Comment by Alfagun74** [comment]
Makes sense UX-wise but is not a bug, rather a missing feature

**Comment by KairuByte** [comment]
Fair enough, I was torn between the two. Yes, that is all the issue is about.

**Comment by Alfagun74** [comment]
merged to #191
