### ISSUE TITLE
Unneeded scroll arrows on library edit screen

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#189]
**Describe the bug**
There are unneeded (and disabled) scroll buttons along the right of the instructions for the edit modal within the library.

**Expected behavior**
If these will never be needed they should be removed completely (I've never been able to get them into a state where they enable.) If they actually have a state where they enable, they should likely be hidden on top of the disable when not usable.

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/393806/fe64f370-a27a-4d05-9c6d-27c72616472a)

**Comment by Yelo420** [comment]
Scroll bar arrows are now only displayed when the scrollbar is used
