### ISSUE TITLE
A logout button

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#194]
**Is your feature request related to a problem? Please describe.**
Sometimes, I just want to log out.

**Describe the solution you'd like**
A button to log me out. Maybe under the login button?

**Describe alternatives you've considered**
Not logging out. I dislike this alternative.

**Additional context**
Technically possible by failing to login while already logged in, but this is a terrible workaround.

**Comment by Alfagun74** [comment]
Merged into #198
