### ISSUE TITLE
Uninstall games

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#196]
**Is your feature request related to a problem? Please describe.**
Downloads and extracts can be deleted from the UI, installs should be possible to delete/uninstall as well.

**Describe the solution you'd like**
For portable apps. deleting the folder should be enough. For full blown installs, there should be an entry in the registry which tells you what command to run to kick off the installer.

Portable game uninstallation should require confirmation. Installed game confirmation may not be required, as the uninstaller will almost always require further steps.

**Comment by Yelo420** [comment]
For installations, it would be best to allow the user to choose the "uninst.exe" directly. The question is whether it would be better to offer the same selection method as the actual game (a dropdown with an overview of all available ".exe" files) or to use a file picker for the selection.

**Comment by KairuByte** [comment]
Honestly I think a file picker is the better option. Then again as I mentioned in #243 I think the entire dropdown system needs to be done away with anyway. ;P

**Comment by Yelo420** [comment]
Uninstallation implemented for all game types.
And about the rest: I think I'll rebuild some of this workflow when I integrate the install tab into the library.
