### ISSUE TITLE
Trim executable selection

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#197]
**Is your feature request related to a problem? Please describe.**
Deep folder structures end up with extremely long lines in the selection of executables. Most of the information isn't actually helpful.

**Describe the solution you'd like**
Trim all information to the games root folder.

**Additional context**
This entry would be truncated to `~\Files\UnityCrashHandler64.exe`:
![image](https://github.com/Phalcode/gamevault-app/assets/393806/654ad12b-0546-466a-94d1-db77247aa6d8)

**Comment by Alfagun74** [comment]
I like this idea.

**Comment by Yelo420** [comment]
The selectable executables are now trimmed, in the installation tab
