### ISSUE TITLE
Refactor the Settings Tab

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#198]
**Is your feature request related to a problem? Please describe.**
The Settings tab has gathered quite an amount of tickets that could be joined into one to show it some love. Lets refactor it to make more sense. See #194, #193, #192, #190.

**Describe the solution you'd like**
Restructure the Settings Tab Like this:

Sure, here's a more organized and user-friendly menu structure with descriptive labels for the settings you've listed:

**Application**
- **General**
  - [x] Auto-Load Library from Server on Startup
  - [x] Auto-Extract Downloaded Games

- **Server Settings**
  - [x] Set Server URL

- **Startup**
  - [x] Launch GameVault on Computer Startup
    - [x] Minimize GameVault to System Tray on Startup (only if upper is activated)
  - [ ] #192 Logic

**User**
- **Account**
  - [x] Login
  - [x] Register a new User
  - [x] Log out (only when logged in)
  - [ ] Edit User (only when logged in)

**Data**
- **Ignored Executables**
  - [ ] Editable List of Ignored Exectutables

- **File System**
  - [x] Select GameVault Root Folder

- **Cache Management**
  - [x] Clear Image Cache (1000 MB)
  - [x] Clear Offline Cache (29 MB)

This structure groups the settings into 3 logical categories, making it easier for users to find and adjust the settings they're looking for. The labels have been made more descriptive and concise for better clarity.

Thanks @KairuByte for all the helpful feedback.

**Comment by Yelo420** [comment]
Everything except the logic of #192, the user edit and the Ignored Executables list impemented so far.

**Comment by Alfagun74** [comment]
@Yelo420 I will extract those aspects into seperate tickets again.
