### ISSUE TITLE
Support for more executable files

### ISSUE THREAD

**Issue by 60plus** [Phalcode/gamevault-app#199]
Please add the ability to run the game from a file other than .exe (.bat .lnk .com) or way to add custom attributes/commands to .exe

The reason is that most of the old games coming from GOG use dosBox. To run such a game you need to use the shortcut (.LNK file)  which is the main folder of the game.

![obraz](https://github.com/Phalcode/gamevault-app/assets/73450566/92800308-b1cd-40eb-806d-7cef0f3f097b)

or add custom attributes/command to exe file.

![obraz](https://github.com/Phalcode/gamevault-app/assets/73450566/9d537f56-17fc-4e88-8479-ef7aa55f8e7d)

For example, to run Eye of the Beholder:

DOSBox.exe -conf "..\dosbox_eob2.conf" -conf "..\dosbox_eob2_single.conf" -noconsole -c "exit"

But we can only run Dosbox itself.

![obraz](https://github.com/Phalcode/gamevault-app/assets/73450566/3f4b63b7-e9dc-4241-a0c3-a73d8ab47a5c)

Thanks in advance.

**Comment by Alfagun74** [comment]
I understand your issue but could you not just use START.exe in this particular example?

**Comment by Alfagun74** [comment]
Reseach shows there are a bunch more executable file types on windows:
EXE, BAT, COM, CMD, INF, IPA, OSX, PIF, RUN, and WSH.

Simple solution would be just to allow these files too i guess.

**Comment by Alfagun74** [comment]
I will create another issue for the custom launch parameters

**Comment by 60plus** [comment]
> I understand your issue but could you not just use START.exe in this particular example?

No it is old dos .exe file

**Comment by Alfagun74** [comment]
Alright. Until this feature is implemented, my workaround suggestion is to write a ".bat" file and convert it to .exe using a tool like [Bat2Exe](https://bat2exe.net/) to enable starting the games from GameVault while maintaining app functionality.

Example:
```batch
@echo off
start "" "path\to\DOSBox.exe" -conf "..\dosbox_eob2.conf" -conf "..\dosbox_eob2_single.conf" -noconsole -c "exit"
```

**Comment by 60plus** [comment]
Thank you.

**Comment by Yelo420** [comment]
"EXE, BAT, COM, CMD, INF, IPA, OSX, PIF, RUN, and WSH. (and LNK)" - are now pickable in the installation tab.

Change will be live with the next update
