### ISSUE TITLE
UI Redesign Library & Installations

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#201]
This is a consolidated ticket of #162 and #169.

The plan is to get fully rid of the Installations Tab and instead merge the installed games into the Library. Additionally the Game View needs to be redesigned and we will need to implement the installations tab.

**Comment by Alfagun74** [comment]
Mockup:

![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/eac467de-8a50-4a32-8a02-840cb1d9fe2f)


[Library.pdf](https://github.com/Phalcode/gamevault-app/files/12389150/Library.pdf)

**Comment by yodatak** [comment]
Hello some inspiration an exemple like https://github.com/grimsi/gameyfin does ( would love to have all fonctionality in gamevault  ^^)

**Comment by Alfagun74** [comment]
i spent some more time redesigning:


![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/16f7624f-e60f-45c0-8058-ec19ffd1ccfa)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/51689a79-448e-42b2-a73b-b2b49a992f62)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/f902ee5c-0cc5-44d4-b2c8-20e3a03157a6)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/d0e94ad5-816c-494a-b90b-deb49cc0bcb6)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/52d708da-48ff-4c61-b2e0-194beb645363)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/601bcbc7-d795-458d-b501-804f89d70fa8)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/0952c76c-4fab-4486-9dc2-974e63efd81d)
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/ed8b893e-c08e-42cf-898f-b31382d70820)

**Comment by Alfagun74** [comment]
## To Design by me:
- [ ] Game Settings View
- [ ] Game View

**Comment by Alfagun74** [comment]
last steps tracked in #280
