### ISSUE TITLE
Linux or web client

### ISSUE THREAD

**Issue by PrzemekSkw** [Phalcode/gamevault-app#202]
Windows client works on linux with bottles but it's not nice option. Window is blinking. 
Please consider to make web client or linux client.
Regards.

**Comment by Alfagun74** [comment]
We're actually giving it some serious thought. It's a pretty hefty task, so we're in the process of figuring out the details and timing.

Check out these links for more info: https://github.com/Phalcode/gamevault-backend/issues/172, https://github.com/Phalcode/gamevault-app/issues/155, https://github.com/Phalcode/gamevault-app/issues/177.

Rest assured, we'll definitely keep you in mind as a beta tester once we've got something ready to roll. 😊
