### ISSUE TITLE
Create a button on the Installed Game screen to create a desktop shortcut to launch the selected game

### ISSUE THREAD

**Issue by MisterVertigo7** [Phalcode/gamevault-app#206]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a convenience.

**Describe the solution you'd like**
After installing a game, somewhere on the UI have a button you can click to create a Desktop shortcut to launch the selected game.

**Describe alternatives you've considered**
An option to create a desktop icon during the "install" would also be convenient.

**Comment by KairuByte** [comment]
I'd hazard that you *don't* want the icon created by the game by default, do you? That would bypass GV completely, meaning no ability to track playtime.

**Comment by Alfagun74** [comment]
@KairuByte

No, it's not relevant. GameVaults Watchdog keeps an eye on all executables (excluding the ones marked as ignored) and automatically monitors your Playtime, regardless of how you start the game in the end. As long as it operates in the background, there shouldn't be any problem. (Auto-Starting in minimized mode is the optimal configuration in this case)

**Comment by Alfagun74** [comment]
Honestly i think for now something as stupid as a "Create Shortcut to the selected Exe"-Button in the Install-View would suffice.

**Comment by Yelo420** [comment]
Implemented.
