### ISSUE TITLE
Ability to separate Downloads and Installations folders.

### ISSUE THREAD

**Issue by 60plus** [Phalcode/gamevault-app#210]
Hello.

First of all, I want to thank you very much for this project. Great job.

I just dumped my entire GOG library into GameVault and I ran into a problem with big games. (BG3, Witcher 3, Cyberpunk)

1. Game is first downloaded to `Downloads` folder in compressed format  (100GB).
2. Archive is extracted (100GB + 100GB) because the archive remains to `Re-Extract`.
3. Game is installed (100GB + 100GB + 100GB) in `Installations` folder .

So to install a game with about 100 GB size we need 300GB of free space in GameVault root folder to keep GameVault App functionality.

I propose to add the possibility to setup `Downloads` and `Installations` folders on different drives. Or button to delete compressed archive after extracting before installation.

**Comment by Alfagun74** [comment]
Just in Case this gets implemented: Let's keep in mind that moving files between different disks takes time. So, we should have loading bars in certain spots, such as when we're moving the "Extracted" folder.

**Comment by Alfagun74** [comment]
I think both tickets are similar enough to merge them. Planned in #229.
