### ISSUE TITLE
Cluttered "tab list"

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#211]
**Describe the bug**
When tabbing in the application, unselectable elements are tabbable. This includes things like the main windows view port, and similar elements.

**To Reproduce**
Open the app, hit tab.

**Expected behavior**
Honestly, nothing. But at the very least it should tab through elements that can be interacted with, such as the sidebar or the games.

**Additional context**
This happens throughout the app. If requested I can attempt to find all instances and list them.

**Comment by Alfagun74** [comment]
No bug here! This is called accessibility. It's all about making sure that users with screen readers and impaired vision can understand what's happening on their screen and use the software.
