### ISSUE TITLE
View Error Log Folder Button brings me to the wrong folder

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#213]
**Describe the bug**
The View Error Log button opens the wrong folder.

**To Reproduce**
1. Provoke an Error
2. Click on View Error Log

**Expected behavior**
Should open Error Log folder: ```C:\Users\Administrator\AppData\Local\Packages\Phalcode.174950BD81C41_dymsgn3qpfjxc\LocalCache\Roaming\GameVault\errorlog```

Actually opens:
```
C:\Users\Administrator\AppData\Roaming\GameVault\errorlog
```

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/7db80f1a-08e3-4b1d-8dc4-d738e1c05c88)

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22621.2134
 - Version 1.4.1

**Comment by KairuByte** [comment]
Where *are* the logs? I don't see mention in the Docs.

**Comment by Yelo420** [comment]
Should bei fixed since Version 1.6.2
