### ISSUE TITLE
Error when sorting by recently_added - Descending

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#214]
**Describe the bug**
When i try to sort my games by "recently added" and then by descending i get the following error:

The Problematic Line:
```json
"release_date": null,
```

I think its because release_date is now nullable due to https://github.com/Phalcode/gamevault-backend/issues/180.

Please make it nullable in the Client aswell

**To Reproduce**
1. Go to Library
2. Sort by Recently Added DESC

**Expected behavior**
Should show newest games

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/0fc837ca-da4a-4b14-80f1-746a9b95c41b)

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 1.4.1

**Comment by Yelo420** [comment]
Release Date is now nullable in the Client aswell
