### ISSUE TITLE
Admins should be able to delete user progresses

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#215]
**Is your feature request related to a problem? Please describe.**
The server has just implemented the feature for admins to delete the progress of other users.

**Describe the solution you'd like**
Enable the "Delete Progress" button on all user profiles for admins (with confirmation, of course).

**Comment by KairuByte** [comment]
Would this be on a "per game" level as well, or just "wipe out this users progress completely"

**Comment by Alfagun74** [comment]
Per each game progress, same delete button you have

**Comment by Yelo420** [comment]
Implemented
