### ISSUE TITLE
It is possible to select "[blank]" as an executable option

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#224]
**Describe the bug**
On the "Installs" page, it is possible to select nothing as the executable option. I believe this is a bug, since this breaks the ability to play the game, and "none" is obviously not a valid option.

**To Reproduce**
1. Install a game
2. Click the executable drop down.
3. Click the top most option immediately in the dropdown

**Expected behavior**
Top most option should be the currently selected executable. This state should not be reachable.

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/393806/6fa351f1-4bb8-477f-850f-0a5af688c8f7)

**Comment by Yelo420** [comment]
In fact, this is not a bug. When you click on the dropdown, it just searches for new executables and refreshes the list. 
[blank] is valid in this case, because the play button is deactivated automatically.

If this behavior leads to confusion, then I can also change the behavior. I am open for suggestions.

**Comment by KairuByte** [comment]
I'd honestly still call this a bug. I get that the list is being refreshed, but it should really default to the previously selected item when the list is loaded. Dropdowns shouldn't lose their previous selection when the user goes to interact with them, barring some fringe situations such as the original value no longer being available.

It would also be a good idea to have the fringe "something went wrong" be `[None]` instead of blank.

**Comment by Yelo420** [comment]
Fixed. Will be available in the next Version.
[Blank] is now only possible if no executables exist, or the previously selected executable has suddenly disappeared
