### ISSUE TITLE
Clicking off the edit window makes it disapear (not just within the app)

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#225]
**Describe the bug**
When clicking off the edit screen, the edit screen goes away. This includes not only clicks within the app (more understandable) but also clicks completely outside the application. This means a computer using the search functionality literally has to stare at the box doing nothing until the results come back. (And this is currently over 30 seconds, sometimes longer if the RAWG API is slow.)

**To Reproduce**
1. Go to a game in your library
2. Click on the edit button
3. Add a search term and click 'search'
5. Do literally anything other than watch the box. Click within the app, click the window bar, click your taskbar, hit alt+tab.

**Expected behavior**
Clicking within the app viewport should be the only one of these that makes sense. The others are all interacting with things external to the apps function.

**Comment by Yelo420** [comment]
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/6fb340b2-11f8-4f2e-b3e3-de8c7baf57b1)

Already fixed. Have completely removed these shitty popups. They are now solid Controls and not those subwindows

**Comment by Alfagun74** [comment]
this is what i call processing time
