### ISSUE TITLE
Closing the edit window does not clear it's contents

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#226]
**Describe the bug**
When closing the edit window, I would expect a complete wipe back to default. Currently it remains in it's previous state (actually it continues processing after the close until you return to the library main page if we want to be technical.)

**To Reproduce**
1. Go to a game in your library
2. Click on the edit button
3. Add a search term and click 'search'
4. Close the window by clicking out of it
5. Click on the edit button

**Expected behavior**
Closing the edit should wipe the state of the edit.

**Comment by Alfagun74** [comment]
This isn't a bug; it's a feature. A user should be able to quickly check something before submitting edits. It's much less frustrating than losing all your changes when you click away for a moment. If you leave the game's page, the data resets.
