### ISSUE TITLE
Multiple locations for installs/game libraries

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#227]
**Is your feature request related to a problem? Please describe.**
Large game libraries, or small libraries with large games, will butt up against storage issues. For instance, if a you have 10 games installed with an average install size of 100GB, you're maxing out what a 1TB drive can do. And games are often well over 100GB these days.

**Describe the solution you'd like**
The ability to define multiple "install folders" on different drives.

**Describe alternatives you've considered**
Junctions are an option, but a terrible idea.

**Additional context**
I don't think theres going to be a way around this issue in the long term. Short term it can likely be put on the back burner, but asking users to uninstall games in order to install new ones, when they have multiple drives that can be used to house games would be a silly idea in the long term.

This has the added benefit of being able to install games which would benefit from the read improvement on SSDs, while being able to install storage hungry games on HDDs.

**Comment by 60plus** [comment]
Almost the same what I meant here : [Ability to separate Downloads and Installations folders.](https://github.com/Phalcode/gamevault-app/issues/210)
We definitely need the ability to install on multiple drives.

**Comment by Alfagun74** [comment]
I think both tickets are similar enough to merge them. Planned in #229.
