### ISSUE TITLE
Bury "Documentation/Discord/Ko-fi" in an about page of settings

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#228]
**Is your feature request related to a problem? Please describe.**
I get the intent of these buttons, but they are mostly unnecessary, and slightly confusing. Let me go into detail:

The docs: The end users are virtually never going to use these. They are more for setup of the server than anything, and at the end of the day you want 99% of the application (the part most users use daily) to be self explanatory. The other 1% is power users and admins, who will already know how to find the documentation.

Discord: This is confusing for the end user, what discord is this? And why would I want the button here after I've decided to join, or not join?

Ko-fi: I get the point of this, I do. And I'm not suggesting that you shouldn't be able to make some extra scratch off the app. But the decision to donate will be made on the fly, and virtually never revisited.

**Describe the solution you'd like**
All of these options should be presented during onboarding, and otherwise buried in the settings. The only one I can see needing to be re-presented would be ko-fi, perhapse after the 10th and 100th opening of the application? It should be possible to manually turn this off though, since if a user knows they are most definitely never going to donate, or already have, they shouldn't be pestered as that isn't likely to change their mind.

**Additional context**
I understand the original intent of these links being here, but omnipresent buttons that have a one time use are terrible UX.

**Comment by Alfagun74** [comment]
Thank you for your feature request and the detailed explanation of your concerns. After careful consideration, we believe that the current placement of these buttons aligns with our intended user experience and serves specific purposes. Here's why:

1. **Documentation**: While end users may not frequently access documentation, having quick access to it can be valuable, especially for new users or when troubleshooting. Placing it in a visible location ensures accessibility when needed.

2. **Discord**: The presence of the Discord button allows users to easily connect with the community, ask questions, or seek help. Its location after joining serves as a reminder and encourages community engagement.

3. **Ko-fi**: Providing users with an option to support the app is a common practice. While donations may not be revisited frequently, the option remains available for those who wish to contribute and support ongoing development.

We understand your perspective on the UX, and we continually assess user feedback. However, moving these options to onboarding or settings may reduce discoverability for some users and limit engagement with our community and support channels. I want people to notice these when they have a problem.

Thank you for understanding our reasoning behind the current design choices.
