### ISSUE TITLE
See what version the backend is running from the frontend settings.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#234]
This would allow a user or administrator to quickly know which version the backend is running, making it easier to know if an update may be required.

Todos:
- Implement JSON Object with Server Version in the Health API
- Implement Backend version Indicator in the Server URL Selector:

![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/3adff67d-ca55-4928-a555-ccbd54f979cd)

**Comment by Alfagun74** [comment]
I could implement this into the health API

**Comment by Alfagun74** [comment]
I've refactored the health API quite a bit. now, when an admin calls /health/admin it returns an object like this:

```json
{
    "status": "HEALTHY",
    "version": "8.0.0",
    "uptime": 37,
    "protocol": [
        {
            "timestamp": "2023-10-15T01:19:35.482Z",
            "status": "HEALTHY",
            "reason": "Server started successfully."
        },
        {
            "timestamp": "2023-10-15T01:22:35.482Z",
            "status": "UNHEALTHY",
            "reason": "Database disconnected."
        },
        {
            "timestamp": "2023-10-15T01:40:35.482Z",
            "status": "HEALTHY",
            "reason": "Database reconnected."
        }
    ]
}
```


@Yelo420 now that the Health API returns some really useful additional informations for admins could you build a dashboard tab in the Admin Panel that displays:

- [ ] Server Version
- [ ] Server Uptime
- [ ] Server Health
- [ ] Server Health Protocol

later on we could look into adding [this](https://github.com/Phalcode/gamevault-backend/issues/199) here aswell.

**Comment by Alfagun74** [comment]
moved to https://github.com/Phalcode/gamevault-app/issues/265
