### ISSUE TITLE
Search for Box art image and pick the desired image from frontend (similar to RAWG search)

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#235]
I use https://www.steamgriddb.com/ to get most of my Box Art Images. They have a good selection and usually have what I'm looking for.

Would it be possible to allow for search results (maybe first 10?) to be displayed in the front end so the user can easily select from the options available without needing to go back and forth from the browser. 

This would make it much faster to select Art Images and a smoother user experience.

**Comment by Alfagun74** [comment]
SteamGridDB needs an API key to access their images. And I thought about it at some time before but another API key for our users to sign & set up makes things look very complicated while they are not.

**Comment by Alfagun74** [comment]
We've considered it, but we don't believe it's necessary to add a Google image search feature to the GameVault client at the moment. The Google image search in the background is essentially a web scraping process without an official API, and it comes with significant rate limitations. For now, we recommend using your web browser. We've simplified the process of importing images using #173.
