### ISSUE TITLE
Display Cover Art in the details screen (we could put it under the download/playtime/last played section on the right)

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#236]
It would be nice to see a bigger version of the Cover Art Image (instead of the smaller thumbnail version we usually see) when I click "into" a game.

Maybe a good spot for now would be to the right of the description and underneath the download/playtime/last played section on the right.

A lot of Cover Art is detailed and it would be cool to see it again "closer up."

What do you think?

**Comment by Alfagun74** [comment]
Nice idea but it's already planned in #201

**Comment by Kudjo-Grand** [comment]
Oh, heck yeah, do THAT! Looks way more polished.
