### ISSUE TITLE
Box art quality lowers dramatically after upload and restart of client

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#239]
**Describe the bug**
After immediately uploading box art, the art quality is what would be expected based on the quality of the original image. However, once you restart the client (clearing image cache does not seem to work) the images are drastically lower quality, to the point that it is easily noticeable on a 1080x768 screen.

**To Reproduce**
1. Go to 'Library'
2. Click on any game
3. Click on the edit icon
4. Click on 'Box Art Image'
5. Input an image URL
6. Click save
7. Return to 'Library'
8. Click the search button (to re-grab images)
9. Take note of image quality
10. Restart client
11. Return to 'Library'
12. Take note of new image quality

**Expected behavior**
Honestly, the box-art should likely not be lower quality, and if this is a form of optimization it should really be optional. I'm serving 100GB+ game files, I'm not concerned about saving space or bandwidth on images.

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/393806/784a64dd-2a28-4565-8fe1-e3e62cfd5f04)
Note: Left is after a client restart, right is immediately following an upload.

**Additional context**
URL used in example: https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/library_600x900_2x.jpg?t=1693935520
Image size is a measly 193.37 KB with a density of 600 × 900 pixels.

**Comment by Alfagun74** [comment]
I want to note this may get worse with upcoming UI update, but we aim to fix it soon. Sorry for any inconveniences. Good News is: As soon as a fix is released a simple click to the "Clear Image Cache" button will get all good quality images.

**Comment by Yelo420** [comment]
Fixed
