### ISSUE TITLE
Empty folder left for install if the game is never installed

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#241]
**Describe the bug**
When a game is downloaded, there is no folder in place for the install (as expected). However, once the game has started extraction, the install folder is created. If the user then deletes the installer without ever having installed it, the install folder remains.

**To Reproduce**
1. Go to 'Library'
2. Click on any game
3. Click Download
4. Go to 'Downloads'
5. Click on 'Extract'
6. Click on the trash icon

**Expected behavior**
1. The folder should not be created until the install button has been pressed.
2. When the installer is deleted, if the folder in `Installations` is empty, delete it as well.

**Comment by Alfagun74** [comment]
This is not a bug; it's a feature. In the event that the installation pipeline fails or is not available for some reason, the user will still have the folder available to manually install the game after extraction.

**Comment by Alfagun74** [comment]
Deleting empty installation folders in case the user deletes the download before installing sounds like a good idea though.

**Comment by KairuByte** [comment]
Makes sense to me! Though I'd think that even if the installation pipeline fails, you'd be able to hit that install button to create the folder would you not? Either way, I think the leftover empty folder is the main thing that is an issue so I can get behind the auto creation on extract.

**Comment by Alfagun74** [comment]
We've decided to delete the empty installation folder when removing the download.

**Comment by Yelo420** [comment]
Implemented.
