### ISSUE TITLE
Allow deletion of a download when downloading/extracting

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#242]
**Is your feature request related to a problem? Please describe.**
If I want to delete an install, I shouldn't need to take extra actions.

**Describe the solution you'd like**
If the delete button is pressed, and an action is currently taking place, throw up a prompt (with a "don't show me this again" checkbox) that will allow me to interrupt the current process and delete, without further manual involvement.

**Additional context**
This would obviously not work for installations.

**Comment by Alfagun74** [comment]
The current asynchronous architecture would make it challenging to implement a seamless abort without prior user cancellation, especially for extractions. 

In case of extraction, we launch 7zip subprocesses that we don't directly control and that makes aborting them sychnronously a pain in the ass. 

Please just abort your processes before deletion for now.
