### ISSUE TITLE
Do away with the dropdown for executable in favor of manual entry with a browse button

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#243]
**Is your feature request related to a problem? Please describe.**
Modded games often need to be called by a command completely separate from the executables within the installation folder. Or, they are able to run from an executable but need command line arguments. Similarly, some games have arguments needed to enable certain game or graphic modes, or other such changes to the execution of the game.

**Describe the solution you'd like**
Ideally, the entire executable drop down would go away, being replaced by a text box with a browse button next to it. Limit the browse button to executables, default to the install folder, and most cases will be handled. But this would also allow users to put arguments or completely external executables as the start command.

**Additional context**
An example of Mod Organizer 2 running Starfield shows there is absolutely no mention of the game files: `C:\Modding\MO2\ModOrganizer.exe "moshortcut://Starfield:SFSE"`

**Comment by Alfagun74** [comment]
Please just create a shortcut and use it like described in https://github.com/Phalcode/gamevault-app/issues/199 after client v1.6.0 releases

**Comment by KairuByte** [comment]
Honestly, it seems odd that you'd want a user to move out of the client to create a windows level shortcut, then reference that shortcut within the client. It's also going to be more difficult to describe to a non-technical end user how to make such a change, as it consists of "go to the folder, right click and create a shortcut (hopefully within the same folder,) add these arguments, save it and move it to the folder (if needed,) select it as the executable" as opposed to just "paste this into the executable section."

It'll also be very odd when you support GV shortcuts which launch a game, since you'll be creating a shortcut to tell GV to open a different shortcut that the user manually created to start the game.
