### ISSUE TITLE
Replace first time registration and login which currently use the "old style" popups

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#244]
**Is your feature request related to a problem? Please describe.**
As the title says, first time registration and login (during onboarding/setup wizard) use the old style of popup mentioned in #225.

**Describe the solution you'd like**
Replace with the solid control solution mentioned by Yelo in #225.

**Comment by Yelo420** [comment]
I took another look and found that the self-closing old popups in the setup wizard fit well. 
They do not have to remain open for the image upload. Somehow a closing "X" would be unnecessary there now.
