### ISSUE TITLE
New users do not show on the community page without client restart

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#246]
**Describe the bug**
Newly added users do not display as an option within the community tab until the client has been restarted.

**To Reproduce**
1. Go to the Community tab
2. Click on the user drop down
3. Take note of current users
4. Fully register new user
5. Repeat steps 1-3
6. Note that the user created in step 4 has not been added to the list

**Expected behavior**
Additions/removals of activated users should automatically update when browsing to the tab.

**Comment by Alfagun74** [comment]
That's an awesome idea! We'll implement a list refresh when you enter the Community tab.

**Comment by Yelo420** [comment]
Implemented.
