### ISSUE TITLE
Deleted users are no longer displayed in the Admin Panel unless the corresponding toggle switch is active

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#250]
If you encounter a wave of registration spam and decide to delete all users, the admin panel's list can become quite crowded with the soft-deleted entries. 

We could consider adding a trash tab to recover users and prevent cluttering the main UI with them.

**Comment by Yelo420** [comment]
The current idea is that we do not install a hard delete and that deleted users are only displayed in the list if a toggle switch is active for them

**Comment by Yelo420** [comment]
Implemented
