### ISSUE TITLE
Show Progresses for deleted Games

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#252]
Since https://github.com/Phalcode/gamevault-backend/blob/master/CHANGELOG.md#progress-and-game-display it's possible to show the game details for progresses on deleted games. We have to use it.

![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/21a91d36-ea14-4a23-9c91-2b9c39247325)

Currently you cant identify those games, cant open them and cant delete them either.

- Seeing the games title and image aswell as the deletion should be possible

**Comment by Kudjo-Grand** [comment]
Adding more detail to OP, this is what the UI does when we try to delete:
![image](https://github.com/Phalcode/gamevault-app/assets/25695143/15abb6c7-4a32-4185-82dd-1923ef052791)

hope it's useful.

**Comment by Yelo420** [comment]
Fixed. Will be available in Version 1.6.1
