### ISSUE TITLE
"Instant" (Indexed) Search

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#256]
Would it be possible to implement indexed searching to allow for "instant" or "live" search results? (Results display as you're typing)
This would eliminate the need to ever actually click on the "search" button itself. (Maybe it could be changed to "update index" (or similar) and pull latest info from the backend server)

I just know that for my use flow and my library of over 300 titles so far, search is becoming more important, and it would make things that much faster to find.

What do you think?

**Comment by Alfagun74** [comment]
I love this idea!!!

@Yelo420 now that the search is actually highly performant you could implement a realtime typing search using a debounce timer.

**Comment by Alfagun74** [comment]
Moved to #264
