### ISSUE TITLE
Add "auto install" and "auto delete install files" option for portable games

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#259]
Since portable titles only need unpacking and copying to their final destination, I think it would be nice to allow the user the choice of automating the "install" and removal of install files for these titles. This would allow for a more streamlined flow of getting the game up and running for the end user. Also, it would help save on disk space since the user wouldn't have to remember to remove the install files if they were meaning to.

To be clear, I LOVE that the user can keep the install files, so, I don't want that to go away. Just automate the removal if the user chooses to. (maybe they're installing a bunch of games at once, like I have been. It would just save time.)

I'm thinking to two toggles right by the "Auto Extract Downloaded Games" toggle in the settings menu.

"Auto-Install Portable titles" OFF <---> ON
"Auto-Delete Install files of Portable titles on successful installation" OFF <---> ON (clear, but kind of wordy)

What do you think?

**Comment by Alfagun74** [comment]
Although i would want those settings to be off by default i would still like to have these options. Good idea imo.

**Comment by LoganJFisher** [comment]
I would definitely like auto-install as well.

**Comment by Alfagun74** [comment]
I've changed my opinion regarding this.

I now also think Auto-Extract & Auto-install Portable Titles should always be on, as long as users have enough space on their disks. It's the most intuitive.

Auto-Delete should be optional and off by default.

**Comment by Kudjo-Grand** [comment]
I agree with you. Auto-delete should be an option that is off by default.

**Comment by Kudjo-Grand** [comment]
Is this straightforward to implement?

**Comment by Yelo420** [comment]
Implemented.
