### ISSUE TITLE
Problems with Progresses 

### ISSUE THREAD

**Issue by Yelo420** [Phalcode/gamevault-app#260]
1:Kann durch state Switch erzeugte progresses nicht löschen 

2:Bei einem Progress wurde statt der state zu ändern ein doppelter Eintrag hinzugefügt.
   In dem Fall von unplayed zu completed

Alle Testdaten beim devuser

**Comment by Alfagun74** [comment]
Seit wann sind unsere Issues auf Deutsch bro 💀 HANZ GET ZE FLAMMENWERFA @Yelo420

**Comment by Yelo420** [comment]
oh ja sorry, hab einfach auf Lock 🤙 den Inhalt von meinen Notizen copy pasted. @Alfagun74

**Comment by Alfagun74** [comment]
fixed, war eh nur dev version
