### ISSUE TITLE
Allow .bat, .sh, or .lnk from the install executable dropdown.

### ISSUE THREAD

**Issue by wiseoxejah** [Phalcode/gamevault-app#261]
**Is your feature request related to a problem? Please describe.**

Some games, such as those purchased from GOG, have multiple installer files. This usually happens when DLCs are included. I'm focusing a lot of effort on convenience for my less tech-savvy family members, so having them manually run the DLC installers or select and run them each from the install dropdown is not ideal.

**Describe the solution you'd like**

A possible solution would be to allow selection of .bat or .sh scripts in the installer dropdown. This would allow server admin to include a script in their archive that runs each installer sequentially.

**Describe alternatives you've considered**

Another solution would be to allow .lnk shortcuts to be selected from the dropdown. This would allow us to link to whatever script or executable we choose.

**Comment by Alfagun74** [comment]
Hi @wiseoxejah, this is already possible!

See [Issue #199](https://github.com/Phalcode/gamevault-app/issues/199#issuecomment-1723126822)

**Comment by Alfagun74** [comment]
Although i dont think `.sh` files are supported in that dropdown yet. @Yelo420 Can you add `.sh` to the list please?

**Comment by Yelo420** [comment]
Added '.sh' to the list. Will be available in the next update.

**Comment by Alfagun74** [comment]
@Yelo420 I've reopened this. @wiseoxejah was referring to the dropdown for installer selection. Please include all executable file types in all executable selections within GameVault.

**Comment by Alfagun74** [comment]
![Uploading image.png…]()

**Comment by Yelo420** [comment]
Implemented. Will be available in the next Version.
