### ISSUE TITLE
Display size of stored setup/install files in the "Downloads" tab.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#262]
I know that the size of the game is displayed in the Library before you download it. But, after it's been downloaded, the size is no longer displayed because it is replaced with the "Go To" button (which is fine). What I WOULD like is to see the size of what's been downloaded displayed in the Downloads screen so I can have an idea of what's taking up space. And right now, the only way to do that, seems to be to inspect the file by using the "open directory" button (or manually navigating to the file location in a file manager).

I'm thinking just put it on the right side of the displayed game "card". Maybe the bottom-right. That area seems to have some room to spare.

What do you think?

**Comment by Alfagun74** [comment]
I like the idea but don't like the proposed placement. Maybe we should just show the size of the download and install folder next to the uninstall game and delete download button on the UI respectively?

Like: 32,2GB (Trash Icon)

**Comment by Alfagun74** [comment]
And for the Download Tab Card i would suggest summing up the size of the download **and** the extracted folder, so a user knows how much space is (really) taken by one game.

**Comment by Kudjo-Grand** [comment]
These are both great ideas. One for uniform placement of size information and the other a more complete idea of used space. Good thinking!

**Comment by Yelo420** [comment]
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/96bd3f80-ae63-42a1-bede-2c70e49903a8)

Here both variants in one

**Comment by Kudjo-Grand** [comment]
Nice. I love the "glance-able" design here. Informative, easily seen, not in the way. SHIP it!

:D

**Comment by Alfagun74** [comment]
I don't really like the size of the text and that it separates the folder and delete icon. Would it be possible to make the delete icon look like the download icon in the library where it shows the size below it very small?

**Comment by Yelo420** [comment]
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/bf1f3977-85a3-4b11-9bcb-f86a53f2ff66)

**Comment by Yelo420** [comment]
We have discussed this again and I have now implemented it without brackets
