### ISSUE TITLE
Display download progress in the Game's Library card after you click "Download"

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#263]
Some additional feedback in the UI would be nice for the user.

I think if we added the current download details (same progress bar found in the "download" tab) in place of the download button after the user pushes it could be nice. It would also provide basic details to the user that would minimize the need to switch to the download tab until later.

What do you think?

**Comment by Alfagun74** [comment]
too complicated for now, but we may will consider it after the huge UI changes planned in #201
