### ISSUE TITLE
Add Gamevault to Chocolatey store

### ISSUE THREAD

**Issue by JamesDAdams** [Phalcode/gamevault-app#272]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Gamevault to Chocolatey store

**Describe alternatives you've considered**
Add Gamevault to Chocolatey store

**Additional context**
Chocolatey ❤️

**Comment by Alfagun74** [comment]
I thought about it, created an account, and then did some research. I found out that all supported operating systems already come with a built-in package manager called "winget." Installing GameVault using "winget" is as simple as running this command in your PowerShell:

```ps
winget install gamevault
```

Do you really need Chocolatey? Integrating it into our system would be a complex job.

**Comment by Alfagun74** [comment]
After careful consideration, we decided against fulfilling this request based on the reasons above. Thank you anyway.
