### ISSUE TITLE
Offloading support

### ISSUE THREAD

**Issue by ripsawuk** [Phalcode/gamevault-app#279]
**Is your feature request related to a problem? Please describe.**
I would love to see support for offloading game files automatically back to the server. I currently use offload manually to my unraid server and use 7zip to directly extract games back to my main PC if I decide to play them again.

**Describe the solution you'd like**
Having a feature or option to 'zip and offload' existing game files from the client to gamevault server for later use.

**Describe alternatives you've considered**
I continue the use of my existing 7zip command to zip games and offload them manually, and then write small .bat commands for 7zip to pull them back and directly extract from where they came from. 

**Additional context**

**Comment by Alfagun74** [comment]
If I understand your original issue correctly, you are interested in keeping your saved games, right?

We currently don't have plans to add a feature for zipping and offloading game data in GameVault. This approach doesn't seem like a good strategy for saving your progress, as it would involve saving your entire game folder. Technically, this is horrible, as games store their data in different locations outside of the game folder, such as in appdata or the registry. Also there would be ten 150GB Assassins Creed Valhalla Offload of your ten users who played this game, with a huuuuuge amount of duplicate data which makes my toes curl.

However, if your main concern is preserving your progress through offloading, you might want to explore [this issue](https://github.com/Phalcode/gamevault-app/issues/151) where we have been discussing cloud saves (meaning hosting your own GameVault server).

Another issue to that will follow once we finalize our thoughts. Thank you for understanding.
