### ISSUE TITLE
Switch places of "Uninstall" Button and "Open Directory" Button in Game Settings -> Installations

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#286]
**Describe the bug**
UX-Wise a primary or non-destructive action should be on the right while a destructive action like uninstalling should be on the left.

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/c12ce8e7-1af3-45e1-934f-1983ea0fff38)

**Desktop (please complete the following information):**
 - Version 1.8.0 EA

**Additional context**

**Comment by Yelo420** [comment]
Because its better for the eye, the Buttons are now like this
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/9e7d31bd-7afb-48b0-abcb-0973becfc0c8)
