### ISSUE TITLE
Find Images using Google Icon not centered

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#288]
**Describe the bug**
The Google Icons are not centered vertically in the button.

**To Reproduce**
1. Go to Game Settings -> Edit Images

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/681c5f12-6471-41b8-8315-689da879ee67)

**Desktop (please complete the following information):**
- V1.8EA

**Comment by Yelo420** [comment]
Fixed.
