### ISSUE TITLE
Changing the Profile Picture of another user changes My profile Picture in the top left.

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#294]
**Describe the bug**
Changing the Profile Picture of another user changes My profile Picture in the top left.

**To Reproduce**
1. Change PFP of another User
2. see top left corner

**Expected behavior**
Mine should stay the same

**Additional context**
Restart is the only workaround

- Version 1.8EA

**Comment by Yelo420** [comment]
Fixed
