### ISSUE TITLE
Default Release-Date Filters don't work when i have no release year set in my existing games

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#295]
**Describe the bug**
The default release-year filters are hiding games, where no release date ist set:
Users always had the ability to have no release date so this **must** be fixed ASAP.

**To Reproduce**
1. Use current values (1980,2023) as Placeholders.
2. Remove default values for date filters so the filter is not set on every search by default

**Expected behavior**
Should show games without release_date in filename.
**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/be18dbdd-d324-4a3c-bd10-bf4e4a5f7e47)

**Additional context**
- v1.8 EA
- https://discord.com/channels/1100920639667306496/1187894735336116254

**Comment by Yelo420** [comment]
Fixed
