### ISSUE TITLE
Show that, and how many, filters are applied, even when the filters are collapsed

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#296]
**Is your feature request related to a problem? Please describe.**
A client should be aware that filters are applied, even when the filters are minified.

**Describe the solution you'd like**
Color the filter icon and show a small number next to it when filters are being applied.

**Additional context**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/79a06b27-b2fa-4180-85a2-c2595fd45d67)

Version 1.8 EA

**Comment by Yelo420** [comment]
Implemented
