### ISSUE TITLE
Sometimes i can submit a new image (e.g. box-art) before it is even fully-loaded

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#298]
**Describe the bug**
Sometimes i can submit a new image (e.g. box-art) before it is even fully-loaded. Then the game shows as grey box in the library.

**To Reproduce**
Happens sporadically
**Expected behavior**
Should not enable Save button until the image is really ready to be uploaded

**Additional context**
-v1.8 EA

**Comment by Yelo420** [comment]
Fixed.
