### ISSUE TITLE
add loading indicators to searches and new image preload

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#299]
**Is your feature request related to a problem? Please describe.**
when the server is busy or the connection is slow. GameVault should show spinning loading indicators to make sure the user knows the client is waiting for a server-response.

**Describe the solution you'd like**
- [x] Loading indicator for Search
- [x] Loading indicator for RAWG Search
- [x] Loading indicator when the client pre-loads an image for an upload.

**Additional context**
While my server was busy compressing an image i saw that this list here was just not appearing. It was horrible.

![image](https://github.com/Phalcode/gamevault-app/assets/22225051/9683b5b4-cba3-436f-963e-2dd864b51a76)

**Comment by Yelo420** [comment]
Added loading indicators by using the cursor loading

**Comment by Alfagun74** [comment]
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/7e2333c3-9d51-4019-8df2-5f9794aa6700)

**Comment by Yelo420** [comment]
![afc01b9c-c992-4556-ba6c-32f7a6efed8c](https://github.com/Phalcode/gamevault-app/assets/88632464/9fad76bf-3a49-4ae4-b735-8040f187b79b)
