### ISSUE TITLE
Scrollbar not scrolling outer Scrollview when scrollint to top of inner scroll-view

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#301]
**Describe the bug**
Scrollbar not scrolling outer Scrollview when scrollint to top of inner scroll-view

**To Reproduce**
1. Scroll outer scrollbar down
2. Scroll inner scrollbar up

**Expected behavior**
it should scroll the overflow scrolling on the outer scrollbar

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/e2ca4ca8-5d0a-4448-bd08-b162b22f7a71)

**Desktop (please complete the following information):**
-V 1.8 EA

**Comment by Yelo420** [comment]
Implemented.
