### ISSUE TITLE
Show proper error when searching and the server is offline

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#304]
**Is your feature request related to a problem? Please describe.**
Server/Connection errors when searching should lead to something like:

Offline Troubleshooting: 
https://gamevau.lt/docs/troubleshooting/#unable-to-connect-to-server--500-internal-server-error

**Additional context**
this was originally in #280

**Comment by Yelo420** [comment]
Should it be replace this, when the search failed because of connection or server error?
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/7202950a-5ded-4023-89f7-675310d72dbf)

**Comment by Alfagun74** [comment]
No iirc we designed another image for this case.

**Comment by Alfagun74** [comment]
This one:

![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/efd9f853-0bb7-4cd5-a864-d4003792b77e)

**Comment by Alfagun74** [comment]
And then some text like: "Connection Error"

**Comment by Alfagun74** [comment]
i definitely want better distinction why the Server connection failed so the user can troubleshoot and understand the problem fully.

**Comment by Yelo420** [comment]
Implemented.
