### ISSUE TITLE
Show early access flag in game-view UI

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#306]
**Is your feature request related to a problem? Please describe.**
I have no idea if the game i see rn is early access or not

**Comment by Yelo420** [comment]
Where should i display this?

**Comment by Alfagun74** [comment]
Just make it look like the other genre pill shapes and append it to the existing ones, but it only gets displayed when the game is Early access.

**Comment by Yelo420** [comment]
Implemented.
