### ISSUE TITLE
Show date where this game was added to the server in game-view UI

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#307]
**Is your feature request related to a problem? Please describe.**
I dont know when a game was added to the server, but i can sort by that metric, so i should see it.

**Comment by Yelo420** [comment]
Where should i display this?

**Comment by Alfagun74** [comment]
I think displaying it on the lower left corner of game settings, just like we display the user creation date in the user settings would be fine

**Comment by Yelo420** [comment]
Already shown in the "RAWG Integration" Tab

**Comment by Alfagun74** [comment]
you are right it seems i have already thought of this. sorry!
