### ISSUE TITLE
Cant scroll using scroll-wheel in installed games list

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#310]
**Describe the bug**
I have to click the scroll bar manually.

**Additional context**
-V 1.8

**Comment by Yelo420** [comment]
I don't quite understand, because this is a horizontal scrollbar

**Comment by Alfagun74** [comment]
my wish would be that you would translate the scrollwheel to scroll this view horizontally.

**Comment by Yelo420** [comment]
I think that is a matter of preference. Personally, I find it confusing. Maybe we'll open a pull

**Comment by Alfagun74** [comment]
No poll necessary. I understand your point, but at least allow horizontal scrolling, as my mouse supports side-scrolling and it doesnt work either :(

**Comment by Yelo420** [comment]
Not necessary as soon as https://github.com/Phalcode/gamevault-app/issues/311 is implemented
