### ISSUE TITLE
Sort installed games by "last played"

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#311]
The Installed Games Section should be sorted from most recently played game (left) to most abandoned game(far right) like described in the design document.

**Comment by Yelo420** [comment]
Tricky in combination with the offline cache, where i can not access "Last Played". Any ideas?

**Comment by Alfagun74** [comment]
I mean the client knows best what was last played right? :D We only need to save it.

We could convert the gamevault-exec file to a gamevault-metadata.yaml file and save stuff like

```yaml
executable: bin/Win64_Shipping.exe
last_played: 2024_01_05_.... 
```

In the future we could add more relevant metadata to it

**Comment by Yelo420** [comment]
Good Idea. It is already ment to store multiple data. I will write it to this file. But that means it's actually a "played last on this machine". But I think that's okay

**Comment by Alfagun74** [comment]
i think so too but please rename the file

**Comment by Yelo420** [comment]
Implemented.

**Comment by Yelo420** [comment]
Process optimized. It is now faster and less complicated, with fewer file accesses required
