### ISSUE TITLE
I also expected to be able to scroll wheel in the installed games area

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#313]
Much like https://github.com/Phalcode/gamevault-app/issues/310, I also expected to be able to scroll through the installed game section (even if it is horizontal at the moment).

While auto-sorting will help reduce the need to scroll at all, it won't make scrolling when desired easier.

I don't think there would be any confusion with horizontal scrolling with the noise when unless there was a horizontal AND a vertical axis. But since there's only one, the expected behavior, for me, was that mouse wheel scrolling would move the slider.

Any way we could add that in to make things that much easier for when scrolling is desired? (Some of my users, myself included, tend to have multiple games installed at once. So, this comes up often in my use case.)

**Comment by Kudjo-Grand** [comment]
Something to consider:

As I'm thinking this through, maybe it would be easier in general to make the installed games area scroll vertically like the server games list does. Then it's consistent for the user.

What do you think?

**Comment by Alfagun74** [comment]
horizontal list was a clear design choice, we're not going to change, mainly to have space to always see both installed games and server games at once.

But we casted a poll: https://discord.com/channels/1100920639667306496/1134621163767730217/1193365209897771118

**Comment by Yelo420** [comment]
Should the area of the Installed games scrollbar still be used as vertical scroll for the outer scrollbar if the Installed games scrollbar is not active (because not enough games are installed)?

**Comment by Yelo420** [comment]
Implemented. I will close the ticket for now. If you have any concerns, please feel free to comment here

**Comment by Alfagun74** [comment]
> Should the area of the Installed games scrollbar still be used as vertical scroll for the outer scrollbar if the Installed games scrollbar is not active (because not enough games are installed)?

I think so yeah. Same goes for:
You scroll to the end of the installed games scrollbar, then, if you scroll further via mousewheel, the outer scrollbar should scroll down.

Same for the way up.
