### ISSUE TITLE
use the scroll wheel anywhere on the "downloads" tab

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#315]
It would be nice if I could use the scroll wheel anywhere on the "downloads" tab. Because I just noticed that I cannot scroll with the mouse wheel in the "downloads" tab unless I'm hovering over where the list of pictures are in the middle (instead of being anywhere on the page like the expected behavior was.)

What do you think?

**Comment by Yelo420** [comment]
Should the visual scrollbar stay in the center beside the download cards but its possible to scroll anywhere in the download tab. Or should the scroll bar should go to the outer right of the screen?

**Comment by Alfagun74** [comment]
Do as you like

**Comment by Yelo420** [comment]
Here the Version, where the scrollviewer is stretched over the whole page
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/0ebe87d8-1fe9-4b8d-9e43-ebef9bd8e939)
Does this look off?

**Comment by Kudjo-Grand** [comment]
Nope. Looks consistent with all the other times a scroll bar appears (that I can think of, anyway).

I like it.

**Comment by Yelo420** [comment]
Implemented.
