### ISSUE TITLE
Background image for game details screen

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#316]
It could be nice to re-use the selected box art as the background image if no other image is selected. (that way there's SOMETHING there)

Also, could you allow the user to toggle between a clear background image (as find in server 9.0.4) and a fuzzy one (as currently in 10.0.1)? 

My use case: The background image helps me remember/discover the type/flavor of game it is (fps, 3rd person, bird's eye, etc.) and having a clear image allows me to do that more easily.

What do you think?

**Comment by Alfagun74** [comment]
We do not like the idea of using 9:6 ratio images as a fullscreen 16:9 background. 

We thought about this problem and decided to provide a custom designed GameVault Artwork in the background of Games without a Background Image.

We will introduce a blur/unblur option in the settings.

Please create seperate tickets for seperate problems in the future.

**Comment by Kudjo-Grand** [comment]
Oops. You're totally right. That was two different things. (Related, but separate.) I'll try to be more mindful to reduce your load. Thank you for the reminder.

I don't like the ratio mismatch either. The idea was just so that _something_ other than black was there, your solution of a default background should do nicely. Thanks putting some thought into it.

**Comment by Yelo420** [comment]
Implemented
