### ISSUE TITLE
Users who play this game list doesn't scroll like expected.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#317]
I just noticed that if many users have played a game, you cannot see all of them and cannot scroll down to see the rest (like I was expecting to be able to).

![image](https://github.com/Phalcode/gamevault-app/assets/25695143/d54a24b2-8d4a-464c-9e50-45c6be680d1d)

I can't see details for that user on the bottom or anyone below it (even though I know there are more).

**Comment by Alfagun74** [comment]
Already fixed
