### ISSUE TITLE
Add details to ring chart display.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#319]
I REALLY like the ring chart! It looks great and it's easy to read.

Could we pretty please have the values displayed next to the ring? (That way we don't have to mouse over each section to find it)

![image](https://github.com/Phalcode/gamevault-app/assets/25695143/958516e3-ad29-4e60-bed9-fc63960e729a)

**Comment by Yelo420** [comment]
I can understand that it is a bit inconvenient to have to hover over everything for the information. I'll add a display to the right that shows all the values at the same time. The hover effect should then be completely removed. What do you think?

**Comment by Kudjo-Grand** [comment]
I like the hover effect. Plus, it makes it easier for the user to identify indicated space more quickly when they ARE using the ring chart. I vote to leave it in.

**Comment by Alfagun74** [comment]
I'd like to keep hover aswell

**Comment by Yelo420** [comment]
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/2c793179-8497-49af-978f-239fdf94732d)
Is this already ok like this, or should the percentages also included into the legend?

**Comment by Alfagun74** [comment]
I think @Kudjo-Grand wanted something like:
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/5bc5a2f4-dfe3-4469-81f3-ef4b4dfcfb14)

@Kudjo-Grand could you please just do some paint mockup of how you imagined this?

**Comment by Kudjo-Grand** [comment]
@Alfagun74 nailed it. This IS what I was thinking.

**Comment by Kudjo-Grand** [comment]
![Ring Chart example](https://github.com/Phalcode/gamevault-app/assets/25695143/6e65f71e-3276-4a1e-919f-77685aa85d21)

 
The Yellow-colored values would show up on mouse hover. (or maybe be present ON the ring itself)
And the Green-colored values are always visible.

Was that helpful?

**Comment by Alfagun74** [comment]
unfortunately our chart lib doesnt support lines so this must be good enough:
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/1b6d9ec0-6bd9-4d29-85f3-f70ee7be3afc)

We may replace the lib in the future though
