### ISSUE TITLE
Tweak icon so user can quickly identify if a game is already Downloaded or not

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#320]
Is it possible to change the Download Icon to something different if the Game is already downloaded? Maybe even just change the cloud icon color to blue or purple or something. (Just something that the user can quickly identify if it's already Downloaded or not)

![image](https://github.com/Phalcode/gamevault-app/assets/25695143/4fea1bc9-e1c5-4b13-bbb1-372a566c5f9d)

![292932987-8d2a7e6f-ee14-46e2-963f-b925caf6ac1d](https://github.com/Phalcode/gamevault-app/assets/25695143/f4064cd9-2241-4daa-bfee-cb2f7176888a)

**Comment by Kudjo-Grand** [comment]
![glyph_download_alt](https://github.com/Phalcode/gamevault-app/assets/25695143/a769fecb-2e9e-4f06-8246-02a8290dcda7)

![glyph_download_alt_color](https://github.com/Phalcode/gamevault-app/assets/25695143/1751dd68-a551-465c-bc01-94e260afc456)


Or maybe something like these?

**Comment by Kudjo-Grand** [comment]
![glyph_download_alt_color_proper_purple](https://github.com/Phalcode/gamevault-app/assets/25695143/65d9b592-2400-4eef-8a8a-579da347afef)
 
Proper Purple Prepared!

**Comment by Kudjo-Grand** [comment]
![example](https://github.com/Phalcode/gamevault-app/assets/25695143/e9591222-d997-4067-8e9e-0ed3b909e6b4)

![example_purple_color](https://github.com/Phalcode/gamevault-app/assets/25695143/29fb659b-b845-477f-8d83-8f5b3dab47f2)

Here's what it would look like.

**Comment by Alfagun74** [comment]
hey there @Kudjo-Grand, it's awesome to see you actually sat down and designed something for us. Unfortunately we try to use vector graphics, but i quickly designed my own. What do you think?

![image](https://github.com/Phalcode/gamevault-app/assets/22225051/b6fe7cc2-c193-425e-9b98-b7e888ad7b55)

We plan to use this in white whenever a game is already downloaded :)

**Comment by Kudjo-Grand** [comment]
Awesome! Looks great. 

Did you use inkscape or something else to create the vectors?

**Comment by Alfagun74** [comment]
Inkscape is love

**Comment by Yelo420** [comment]
That the icon changes when the game has already been downloaded is clear, but I'm not quite sure about the color change.

**Comment by Alfagun74** [comment]
That's great we already decided not using colors anyway there

**Comment by Yelo420** [comment]
Implemented.
