### ISSUE TITLE
"Delete system32" in client context menu is not funny

### ISSUE THREAD

**Issue by DX37** [Phalcode/gamevault-app#322]
**Your Question**

Why the hell this exists here?
![изображение](https://github.com/Phalcode/gamevault-app/assets/12829428/7bb9ac6b-fba9-48f2-9fad-e5aa5c352771)

According to code, after choosing this, client will show Windows 10 style BSOD picture in full screen.

![изображение](https://github.com/Phalcode/gamevault-app/assets/12829428/287e565f-1066-4e01-867d-b12182c48bbd)

This behavior is not friendly and welcoming for not experienced users.

![изображение](https://github.com/Phalcode/gamevault-app/assets/12829428/e2979151-54f4-4552-929a-2669cdc11002)
![изображение](https://github.com/Phalcode/gamevault-app/assets/12829428/6d7fbd49-063c-4f3c-85f9-836f191069a5)

**Comment by Alfagun74** [comment]
why so mad? 😂

The reason why this exists is because the developers of this software have a sense of humor. :)

**Comment by Alfagun74** [comment]
We'll remove it soon, but you can be sure, there will always be another easter egg in GameVault. 🙂

**Comment by DX37** [comment]
> We'll remove it soon, but you can be sure, there will always be another easter egg in GameVault. 🙂

Well I thinking of hosting GameVault for my friends and if they encounter this "issue", by choice or by mistake, they will not be glad at first.


> We'll remove it soon, but you can be sure, there will always be another easter egg in GameVault. 🙂

Just friendly ones, please :)

**Comment by Alfagun74** [comment]
It's harmless

**Comment by DX37** [comment]
> It's harmless, it really sounds like you stepped right into our prank, got scared and are now mad af. Lmao.

On the contrary, I immediately realized that this was some kind of joke. I even suggested the pull request above to remove it.

Of course, if you think about it, only slightly more advanced users will be able to use the client anyway. It's just that I used to work in the technical support department and all these extra buttons (especially with jokes) will just push users away.

It just turns out that if I offer someone to install a client, then I will definitely have to say "Well, now you can download and play such and such games, but only if you want to open or close the client, then the main thing is not to be scared, the "Delete system32" button does nothing, it's just a joke lmao and if you accidentally press, then do Alt+Tab and close this window with a picture of the blue screen of death lol."

But anyway, this is your development. I'm not angry or offended, I just suggested getting rid of the unnecessary joke. You don't have to remove it, I'm not forcing anyone here...

**Comment by Yelo420** [comment]
I think it's time to come up with something new anyway.
