### ISSUE TITLE
GameVault not checking read+write permission of root folder 

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#326]
**Describe the bug**
You can select a Folder without any write permissions on it.

GameVault should prevent this from happening or warn the user that there are permission issues.

**To Reproduce**
1. Create a Folder without Perms
2. Use as Root Folder
3. Try downloading a Game

**Expected behavior**
Error showing the user has no root folder permissions.

**Comment by Yelo420** [comment]
Implemented.
