### ISSUE TITLE
Log all catched Exceptions into the GameVault Logfile

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#327]
**Describe**
To help debug stuff it would be great if we could log exceptions that are being catched and handled. So we can easier find out what exactly happened if a user encounters any problems.

Currently GameVault only logs fatal exceptions that are unhandled.

**Comment by Yelo420** [comment]
Will not be necessary because of [this](https://github.com/Phalcode/gamevault-app/issues/328)
