### ISSUE TITLE
Improve Errorhandling by removing "Could not connect to server"

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#328]
**Describe the bug**
Please use clearer Error descriptions than default "Could not connect to server". They dont help anybody.

There are at minimum 10 different places with this error. Use more diverse errror messages so we can find pain points faster and the user knows whats wrong. The GameVault Server usually responds with a perfectly understandable error message in the response body.

When encountering errors the server response Body looks like:
```
{
	"message": "Game with id 1242525 was not found on the server.",
	"error": "Not Found",
	"statusCode": 404
}
```

For example:
"HTTP Error 401: You are not authorized to change this"
"HTTP Error 404: User was not found"

etc.

even if the errors dont originate from the server you could do messages like:
"Could not fetch Users from server: Connection Timed Out"
"Could not login to server: Domain name not resolvable"

**Comment by Yelo420** [comment]
"Could not connect to server" No longer exists. From now on, an attempt is always made to display the server message. If this is not possible, the raw exception message is shown
