### ISSUE TITLE
Admin is able to demote themselves without any other admins present

### ISSUE THREAD

**Issue by Casuallynoted** [Phalcode/gamevault-app#331]
**Describe the bug**
At the moment, if a server has a single admin, they are able to demote themselves to User without any other admins being around, effectively locking them out of the server.

**To Reproduce**
1. Go to Admin panel
2. Click on the admin dropdown next to your name, change to user
3. You are no longer the master of your domain

**Expected behavior**
I would at least hope for a pop up letting an admin know what they're doing, but would ideally be better to have it not allow them to do that unless there are other users assigned as admins.

**Comment by Alfagun74** [comment]
[There is no way to get permanently locked out, as the Server automatically-assigns the admin role to the user specifed in the Environment variable on each startup](https://gamevau.lt/docs/server-docs/user-management#recovering-access-to-admin-user:~:text=If%20the%20admin%20user%20was%20misconfigured%20to%20not%20have%20admin%20permissions%20or%20if%20the%20user%20already%20exists%2C%20the%20server%20will%20automatically%20grant%20admin%20permissions%20to%20that%20user%20upon%20startup.%20This%20ensures%20that%20the%20admin%20user%20has%20the%20correct%20permissions%20even%20if%20there%20are%20configuration%20errors%20or%20existing%20users.)

But i like the idea to show a warning before changing your own role.

**Comment by Yelo420** [comment]
Implemented. Will be available in the next Update
