### ISSUE TITLE
Minor bug, new users can't see the library for the first time

### ISSUE THREAD

**Issue by JoaGamo** [Phalcode/gamevault-app#332]
**Describe the bug**
newly registered users can't see the library for the first time. The actual workaround i've found is asking the user to type anything in the search bar and removing it, forcing a "fetch games list" from server

**To Reproduce**
1. register new user
2. Click on library
3. There's nothing.

**Expected behavior**
The user should be able to see the games list for the first time without these non-user friendly workarounds.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [-]
 - Version [1.8.1]

**Additional context**

**Comment by Yelo420** [comment]
You mean they registered, logged in (without restart) and then switched to the library tab?

**Comment by JoaGamo** [comment]
Correct. I think the steps I mentioned were not descriptive enough
The exact procedure i've seen ,from my windows clients's perspective, is:
1) fresh-install gamevault
2) set the http server link
3) register a new account
4) login with the new account
5)click on "library" button -> No games shown (this bug)

**Comment by Kudjo-Grand** [comment]
I've observed this as well. My workaround was to put Something/Anything in the search bar ("a", for example ), and then remove it. Then, all title on the server would be displayed.

**Comment by Alfagun74** [comment]
We are taking care of it
