### ISSUE TITLE
Clear or edit information for indexed games

### ISSUE THREAD

**Issue by wiseoxejah** [Phalcode/gamevault-app#333]
Sometimes a game is either not listed on Rawg, or the Rawg entry cannot be found by the Gamevault client. If a game like this is added to the library and indexed incorrectly, there isn't an easy way to remove or edit the information manually. This information remains even when (NC) is added to the file name.

One solution that would solve this issue is implementing an option to clear the cached information about a game from within the client's game settings window.

A second solution that would work well alongside the first would be to allow manual editing of all cached information. This way, even if the Rawg information is correct, we could add additional information about the specific copy of each game. This would also allow adding information to games with a NoCache flag, as currently only the images can be added manually.

**Comment by Alfagun74** [comment]
Now that i fully understood your issue i regret to inform you i already have it on the board 😭

https://github.com/Phalcode/gamevault-backend/issues/161

the reason why it is not implemented yet is also there. NC games where not a thing then though so it actually make that ticket even more valid.

**Comment by wiseoxejah** [comment]
That's alright! I should've checked first. I'll check it out here in a bit. Thanks again!
