### ISSUE TITLE
File path is cut off instead of wrapping/scrolling

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#337]
**Describe the bug**
File Path within Game Settings is truncated with no way to view full path.

**To Reproduce**
Have a game with a long file path

**Expected behavior**
At the very least truncate with an ellipsis and display the full path in a tooltip on hover.

Other acceptable solutions:
- Wrap the text
- Scroll the text

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/393806/dd576fa8-59d0-4e7f-ac65-02109d9f6964)

**Comment by Alfagun74** [comment]
yeah this definitely is not beautiful and should scroll/marquee :)

**Comment by Alfagun74** [comment]
@Yelo420 Would be nice if we could fit this into this release.

**Comment by Yelo420** [comment]
Wpf has no scroll/marquee out of the box that does not look like crap. So as easy solution i added text trimming with CharacterEllipsis (...) and additional tooltip insted.

![image](https://github.com/Phalcode/gamevault-app/assets/88632464/a302a5fd-8df8-499b-ba51-4c49320e3ef9)
