### ISSUE TITLE
SteamGridDB Integration

### ISSUE THREAD

**Issue by TheCommandoChicken** [Phalcode/gamevault-app#338]
**Describe the solution you'd like**
It'd be nice to have SteamGridDB integration as an alternative to Google Images and RAWG, since needing to request an API key for the latter is annoying and doesn't scale well. Additionally it could be a good idea to slightly rework the game page layout to better support art in the style used by Steam, but simply automatically cropping the Hero images rather than squashing them would be fine as well.

**Describe alternatives you've considered**
I've been manually downloading images from the site for the time being, but obviously this is pretty inconvenient.

**Comment by Alfagun74** [comment]
We already had look at steamgriddb and it needs an API key aswell, that's why we decided to go for Google images.
