### ISSUE TITLE
Centering Background on Window Resize

### ISSUE THREAD

**Issue by nosyrbllewe** [Phalcode/gamevault-app#341]
**Is your feature request related to a problem? Please describe.**
When you resize the window the background offsets strangely because it is pivoted to the top-left corner.

**Describe the solution you'd like**
I would like it so that the background is centered as it is resized,  resulting in the left-and right borders being cut-off instead of only the right. Essentially, it should fill the screen from top-to-bottom and leave and equal amount cut-off on the left and right. This change should be applied to both the Game pages and Community page (plus any other pages with backgrounds if they exist)

**Describe alternatives you've considered**
I don't really think there are really any alternatives besides pivoting the image to the right of the screen (which would be worst overall in my opinion) and it doesn't solve the issue.

**Additional context**
Here is an example showing the current resizing. 

Original:
![image](https://github.com/Phalcode/gamevault-app/assets/2175256/e9513802-b962-4685-a16b-ccf54d9c95b0)

After stretching the bottom of the window downward:
![image](https://github.com/Phalcode/gamevault-app/assets/2175256/8e623de3-1292-42b7-a02e-d4e4efccc73f)

It feels really weird to me that the image is no longer centered. Additionally, it may cause some background images to not look good if they do no match the aspect ratio of your window as it cuts-off everything to the right..

Essentially, I feel like it should be like the "Best Case" in the top right on the image here instead of the current resizing, which is the top "What I Want" diagram: https://www.gangofcoders.net/solution/how-can-i-fill-a-div-with-an-image-while-keeping-it-proportional/

**Comment by Alfagun74** [comment]
Greatly written ticket and this is definitely not intended, so it's a bug we are going to take care of it ASAP, thanks!

**Comment by Yelo420** [comment]
😨 Oh No, i forget about that one. I'll fix that.

**Comment by Yelo420** [comment]
Fixed
