### ISSUE TITLE
New "re-download" icon not appearing on game tile list view as  expected.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#342]
![image](https://github.com/Phalcode/gamevault-app/assets/25695143/fed166a3-56c1-4add-92a5-511f41b78361)

![image](https://github.com/Phalcode/gamevault-app/assets/25695143/da2bf62f-8f76-475e-ab79-7d9d56158392)

Icon is present when looking at the Game Title Details view, but is not present when looking at the Game Title "Card" in the Server List view.

What do you think?

**Comment by Alfagun74** [comment]
you are totally right. to put it simple: we forgot that one 😂

**Comment by Yelo420** [comment]
The re-download icon is now also displayed in the library. Of course, the "Has already been downloaded, do you really want to overwrite the file" message is also included.

I have also improved the loading time a bit by generating the game card content only when you hover over it with the mouse. This means that all "Is already Downloaded" and "Has permission for settings icon" queries are only executed when hovering. 

Another advantage of the change is that the UI can react immediately to changes (Is Downloaded/Permission changed) without any "refresh".
