### ISSUE TITLE
Refresh button in library

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#349]
**Is your feature request related to a problem? Please describe.**
Adding a game/reindexing currently requires a "manual refresh" of the library panel. This means you need to search something, then clear the search.

**Describe the solution you'd like**
This should not be needed. Every time you go to the library page, it should check if an update is needed at all. At the very least, a refresh button should be added. Even F5 would be welcome.

A reindex should (locally) also kick off a refresh of library data when it completes.

**Comment by Alfagun74** [comment]
I understand why this is frustrating.

Reloading the entire library upon opening it would be horrible for weaker internet connections though.
- Reindexing should already trigger a library reload. If not, it's a bug.
- We could implement a manual refresh button (and maybe F5).

**Comment by KairuByte** [comment]
> Reloading the entire library upon opening it would be horrible for weaker internet connections though.

Agreed, what about an API endpoint that requests the last time a library change took place? This would be useful for third party tools as an API call as well.

> Reindexing should already trigger a library reload. If not, it's a bug.

I'll submit a ticket.

> We could implement a manual refresh button (and maybe F5).

This is also a great idea.

**Comment by Alfagun74** [comment]
@Yelo420 Would be nice if we could fit this into this release.

**Comment by Yelo420** [comment]
Do we still need a "manual refresh button" after [354](https://github.com/Phalcode/gamevault-app/issues/354) is fixed?

**Comment by Alfagun74** [comment]
yes, people ask for this all the time.

**Comment by Yelo420** [comment]
Implemented Library refresh button + can also be triggered by F5
