### ISSUE TITLE
Uninstalling game leaves empty folder

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#350]
**Describe the bug**
Similar to #241, when a game is uninstalled an empty folder remains.

**To Reproduce**
1. Install a game
2. Uninstall that same game
3. Folder remains

**Expected behavior**
If the uninstall is successful, all files are already deleted. At which point the folder is just clutter and should be deleted as well.

**Comment by KairuByte** [comment]
Actually this may be an edge case? It's a windows installer, but I uninstalled after replacing the installer with a portable version.

It didn't ask for an uninstaller, it just deleted the files. 

I'm fine with that, since 99% of the time it's just files that needs to be removed by the uninstaller anyway, but that means there's another bug involved.

**Comment by Yelo420** [comment]
Only the server checks whether it is an installer or portable and forwards this information to the client. Gamevault Client only deletes the files without asking for an uninstaller if it is a windows portable. The game was probably recognized incorrectly (or false flagged)

**Comment by Alfagun74** [comment]
@KairuByte 

Can you still reproduce this and see it as a problem or can this be closed?

**Comment by Alfagun74** [comment]
also see #359

**Comment by Alfagun74** [comment]
Cannot reproduce, author not responding.
