### ISSUE TITLE
Registration failure messaging is extremely unhelpful

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#351]
**Describe the bug**
Any error registering seems to simply state "Server Responded: Please check the server logs for more details." which is out of the ability of most users. In this specific case, it was that the user had already registered with that same email.

**To Reproduce**
1. Register a new account
2. Register another new account with that same email
3. Unhelpful server response.

**Expected behavior**
Tell the user what's up.

**Screenshots**
Reported by an end user, this is the best I have:
![image](https://github.com/Phalcode/gamevault-app/assets/393806/80e153a7-7302-4caa-99c7-461f46c578e3)

In this case server logs had a much clearer answer: `Key (email)=([snip]) already exists.`

**Additional context**
I understand the potential want for security through keeping registered addresses secret, but this really just adds frustration to the registration process.

**Comment by Alfagun74** [comment]
We decided providing a more detailed error here would be the best for everyones sanity

**Comment by Alfagun74** [comment]
should be fixed with server 12.0.0

**Comment by Alfagun74** [comment]
spoiler alert: it wasnt, but now it will be in the next version
