### ISSUE TITLE
User stuck at registration page while already logged in

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#352]
**Describe the bug**
User hit a point after registration where they were logged in, but stuck in the registration wizard. Killing the process and restarting corrected the issue.

**Expected behavior**
Not this.

**Screenshots**
Again, reported by an end user. Not even certain how to reproduce:
![image](https://github.com/Phalcode/gamevault-app/assets/393806/07398b44-557a-4595-a9ec-87417fc91e4e)

**Additional context**
I havent had a chance to attempt to reproduce, but this is likely linked with #351 where the user was already registered, but attempted to register again.

**Comment by Alfagun74** [comment]
we will try to reproduce this and come back to you

**Comment by Alfagun74** [comment]
After logging in, he has to press "Finish" in the Wizard to confirm the onboarding. Or just close it, by navigating anywhere in the sidebar and leaving the wizard.
