### ISSUE TITLE
Admin console sorting, filtering, and view options

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#353]
**Is your feature request related to a problem? Please describe.**
Now that I have more than a handful of users (over 8) the admin console is getting cluttered. Each time a user registers I need to scroll through the list looking for unactivated user accounts.

**Describe the solution you'd like**
Sorting, filtering and a more compact list view option within the admin console.

**Comment by Alfagun74** [comment]
Related: https://github.com/Phalcode/gamevault-app/issues/250

**Comment by Alfagun74** [comment]
The Admin Console in general is outdated and needs a redesign. And i mean both its graphical interface as well as its capabilities. 

Also related to #312.

Maybe we will consolidate these tickets into a larger "The Admin Update" and plan it as a "big" feature.

**Comment by Alfagun74** [comment]
merged into https://github.com/Phalcode/gamevault-app/issues/451
