### ISSUE TITLE
Game reindexing does not kick off a library refresh

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#354]
**Describe the bug**
When a manual reindex ends, the library should be refreshing (as mentioned in #349), however this is not happening.

**To Reproduce**
1. Add a game to the back end
2. Navigate to Admin Console
3. Initiate a reindex
4. After reindex, new game does not show in the library until a search is preformed.

**Expected behavior**
Library should automatically update.

**Comment by Alfagun74** [comment]
@Yelo420 Would be nice if we could fit this into this release.

**Comment by Yelo420** [comment]
Implemented
