### ISSUE TITLE
Resume Download Option

### ISSUE THREAD

**Issue by Bovive** [Phalcode/gamevault-app#355]
**Is your feature request related to a problem? Please describe.**
Currently if a download is interrupted, it must be restarted from the beginning.

**Describe the solution you'd like**
The ability to resume an interrupted or paused download.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Alfagun74** [comment]
Duplicate of [#14](https://github.com/Phalcode/gamevault-backend/issues/14)
