### ISSUE TITLE
Set game background image to float right

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#356]
**Is your feature request related to a problem? Please describe.**
A large number of background options for games are wider than the expected view port. One such source is Steam, which routinely has empty/filler content to the left of an image.

**Describe the solution you'd like**
Float right instead of left. Meaning set the right edge of the image to the right edge of the view port.

**Describe alternatives you've considered**
Leave it as is or choose different images, but sources like steam tend to have higher quality backgrounds following a set guideline of "not to busy, no extra content."

Another option is giving the user an option, or implement a cropping tool into GV.

**Additional context**
Background such as this: https://cdn.cloudflare.steamstatic.com/steam/apps/753640/library_hero.jpg

**Comment by Alfagun74** [comment]
Closed in favour of #341
