### ISSUE TITLE
Confirm to delete the remaining files when Uninstalling a Windows Setup Game

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#359]
I had a rather unpleasant experience uninstalling my Windows Setup Game. I accidentally selected the wrong uninstall executable and closed it. GameVault detected the uninstaller completed and hard-wiped the installation folder after without my confirmation, keeping all the install stuff in the registry...

- [ ] Implement a confirmation check that asks: "The uninstaller was closed. There are 29GB (or 18KB/2MB whatever) of remaining files in the installation directory. Proceed and delete the remaining files?" Yes/No

**Comment by Alfagun74** [comment]
@Yelo420 Would be nice if we could fit this into this release.

**Comment by Yelo420** [comment]
GameVault detects any Files in the Install folders (Because it has no chance to diff trash from the real game). So if the User would click on "Do you want to delete remaining files" - NO
The game would remain installed.

**Comment by Alfagun74** [comment]
That's okay because I selected wrong uninstaller and there is still data

**Comment by Yelo420** [comment]
Because this popup would appear with every Windows setup, it could happen that the user accidentally clicks on NO (uninstall has gone through but there are remaining files). From then on, the user has no chance of deleting the game via the UI and would have to go to the file system.

**Comment by Alfagun74** [comment]
I see.. Another solution would be to put the remaining gamefiles into Windows trash instead of permanently deleting them. This way if I selected the wrong exe accidentally I can still recover them, no popup needed.

**Comment by Alfagun74** [comment]
Or maybe just ask for "are you sure you want to uninstall the game using Uninstall.exe" after selecting the exe. So a misclick doesn't uninstall immediately.

**Comment by Alfagun74** [comment]
We decided to do both.
- [ ] The Popup "are you sure you want to uninstall the game using Uninstall.exe"
- [ ] Move remaining files into trash instead of hard-deleting them and informing the user with a notification.
  - [ ] "Successfully uninstalled game. Remaining 50MB were moved to OS Trash."

**Comment by Yelo420** [comment]
Done
