### ISSUE TITLE
Add "About" Section to GameVault App

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#361]
The RAWG Terms of Service, which our users agree to, state:

> Free for personal use, provided that RAWG is attributed as the source of the data and/or images, and an active hyperlink to RAWG is included on every page where RAWG data is utilized.

The term "Page" is subject to interpretation, but to assist users in complying with this condition and save them from potential legal trouble, we should include a link to rawg.io somewhere within the application, signaling that the data shown may originate from RAWG.IO.

**Comment by Yelo420** [comment]
Where?

**Comment by Alfagun74** [comment]
Sttings -> New Tab Information:

Include information like:
- Application Version
- Legal Notice -> Link to https://phalco.de/legal
- Privacy Policy -> Link to https://phalco.de/
- Third Party Licenses
- Version 
- License (and link to our license.md)
- our company info

**Comment by Yelo420** [comment]
Implemented
