### ISSUE TITLE
More than one installation path and refresh App

### ISSUE THREAD

**Issue by doctorase** [Phalcode/gamevault-app#376]
Hi! I want to request two features for this awesome software.

-Option to more than one Installation path. I have multiple drives, specially HDD and SDD. Usually i install one type of games on HDD an another type in SSD. I would like to install games with Gamevault in different drives like i can do in Steam

-Refresh App feature: If I add a game in the server, is a bit annoying close the App and open again. Would be better a reload/refresh button to load the new added games.

Thanks!

**Comment by Alfagun74** [comment]
Greetings!

1. Is already planned and tracked on our board

2. You can already reindex without closing using the Reindex button on the top right corner of the Admin Tab. To refresh the list just enter something into the search bar then remove it again. The upcoming update will bring a refresh button to the library aswell.
