### ISSUE TITLE
Android app for APKs

### ISSUE THREAD

**Issue by LoganJFisher** [Phalcode/gamevault-app#383]
**Is your feature request related to a problem? Please describe.**
Currently, there is no good system I'm aware of for storing Android apk files in the same manner as gamevault allows for storing Windows and Linux games.

**Describe the solution you'd like**
Create an Android app

**Describe alternatives you've considered**
I've searched for other self-host options that would provide this functionality, but have been unable to find any.

**Comment by Alfagun74** [comment]
I am interested in the concept and we may explore .apk support, along with developing an Android client in the future. However, given the reasons outlined in #284, it is not planned for the near future. 

Nevertheless, the possibility of incorporating .apk support and exploring **Android Emulators** will be considered in #269.
