### ISSUE TITLE
[Suggestion] Use the IGDB API to automatically pull metadata and posters for games

### ISSUE THREAD

**Issue by LoganJFisher** [Phalcode/gamevault-app#384]
**Is your feature request related to a problem? Please describe.**
Unless I'm doing something wrong, games added to gamevault currently lack any metadata (e.g. release year is blank) (and additionally I see no way to edit to manually add such information) and users must manually add an image. Utilizing the [free IGDB API](https://www.igdb.com/api) would allow for both to be automatically pulled from the net, creating a much smoother user experience.

**Describe the solution you'd like**
Add support for the IGDB API to automatically pull game metadata and posters

**Describe alternatives you've considered**
N/A

**Comment by Alfagun74** [comment]
Thanks for the suggestion, but there is already a way to enrich your games with metadata outlined here:
https://gamevau.lt/docs/server-docs/indexing-and-metadata#integration-with-rawg

However the RAWG platform announced, they will soon no longer maintain it is our next big task to find a solution for this. See https://github.com/Phalcode/gamevault-backend/issues/258.

So this ticket is pretty much a duplicate considering the last comment on that ticket :)

**Comment by LoganJFisher** [comment]
Why might my database not be identifying the games I've added. I can understand for a game like The Elder Scrolls IV: Oblivion, as my file is only actually titled Oblivion, but there are other games in my library like Titan Souls that is the proper full name.

**Comment by LoganJFisher** [comment]
Oh, probably because I didn't add a RAWG API key... duh

**Comment by LoganJFisher** [comment]
I added the RAWG API key. Is it only supposed to add metadata? It's adding the metadata but not adding posters. That still needs to be done manually.

**Comment by Alfagun74** [comment]
> I added the RAWG API key. Is it only supposed to add metadata? It's adding the metadata but not adding posters. That still needs to be done manually.

https://gamevau.lt/docs/server-docs/indexing-and-metadata#game-box-arts

Also make sure gamevault has permissions to write to its images volume.

**Comment by Alfagun74** [comment]
> and we have seen some very inappropriate box art show up!

😬😬😬😬😬😬

i knew i should have checked the safe-search parameter of the google scraper 😆

**Comment by LoganJFisher** [comment]
> > I added the RAWG API key. Is it only supposed to add metadata? It's adding the metadata but not adding posters. That still needs to be done manually.
> 
> https://gamevau.lt/docs/server-docs/indexing-and-metadata#game-box-arts
> 
> Also make sure gamevault has permissions to write to its images volume.

I sorta just took the lazy option and left gamevault as root, so it should have whatever permissions it could possibly need.

**Comment by Alfagun74** [comment]
Send me a log of your gamevault server after setting `LOG_LEVEL` to `debug` in your environments, so i can see what is going on. @LoganJFisher
