### ISSUE TITLE
Polish GameVault Update

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#385]
- [x] Golden Dice in lower left corner should just open GV+ Settings Page
- [x] Implement Red Cross if no Subscription is found or not logged in.
- [x] Implement Get GameVault+ Button
  ![image](https://github.com/Phalcode/gamevault-app/assets/22225051/c0e109c5-c769-4bbd-8c80-a70999894f74)
- [x] Implement "You are not logged in" Text instead of "no Active license"
- [x] change these headers so they look like the first one
      ![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/05f80bb7-a514-4dec-b925-a26e038ecbb3)
- [x] Refresh License Flashes Browser for a second
- [x] Dont include timestamp in Dates of License (keep them as hover over) and show them in users local timezone
- [x] Redesign Login/Logout Button to be more User friendly @Alfagun74 
- [x] Explain GV+ in GV+ Settings page including a link for more information @Alfagun74 
- [x] Change Port for Local Auth Redirect for people running something on HTTP-Server instead of 80
- [x] Listen to Mouse Click (Down and Up) instead of only MouseButtonUp
- [x] Reset Theme to default when license expires
- [x] Change "Searching for Updates" Text to "Updating" when applying update in pre-launcher

**Comment by Yelo420** [comment]
Done
