### ISSUE TITLE
Editable Default Launch/Install Options provided by server

### ISSUE THREAD

**Issue by CJCutrone** [Phalcode/gamevault-app#386]
**Is your feature request related to a problem? Please describe.**
I have a few different games that have several launch options necessary in order to run properly (pointing to various files/specifying paths the games needs to know about/etc). Right now I have to have those settings written down somewhere else, so that when I go to download the game I can copy and paste the launch options in my downloaded and installed copy.

**Describe the solution you'd like**
It would be nice to be able to set a default launch option on the game in the server, and have that carried over to the installed version. 

**Describe alternatives you've considered**
Providing a place to store recommended launch options instead of having defaults

**Comment by Alfagun74** [comment]
I'd even go as far as to say it should be possible to set:

- Default Launch Parameters
- Default Launch Executable
- Default Installer File / script to run after download

As a Server Moderator in a special new game settings tab called "Default Options" for all future installations.

**Comment by Alfagun74** [comment]
we need to consider this in https://github.com/Phalcode/gamevault-backend/issues/258

**Comment by Kudjo-Grand** [comment]
If the server admin was able me to post custom content on the game details page, that would give a way to communicate any special instructions with the users too. Not the ideal of total automation (which, I'm sure we'll get to), but straightforward and workable. 

Custom tags could also be used to quickly tell admins and users about games that have special instructions. Making it ready to find in the future. (Like, for example, when a good way is figured out to allow automatically setting launch parameters. Then the admin knows which games need to be visited on the server and updated. Or, the user knows to look for an instruction file or something in the extracted game directory)

What do you think?

**Comment by Alfagun74** [comment]
@Kudjo I think I would like to keep this solution

> I'd even go as far as to say it should be possible to set:
> 
> * Default Launch Parameters
> * Default Launch Executable
> * Default Installer File / script to run after download
> 
> As a Server Moderator in a special new game settings tab called "Default Options" for all future installations.

But additionally, once games are able to be organized in folders, via https://github.com/Phalcode/gamevault-backend/issues/148 we could implement something like a custom README.md File that can be shown on a games page, that is some sort of public note for users by moderators and admins. Similar to the ["Message of the Day" Ticket.](https://github.com/Phalcode/gamevault-app/issues/277)

**Comment by Alfagun74** [comment]
Implemented on the server-side.

Needs to be implemented via https://github.com/Phalcode/gamevault-backend/issues/161 on client side and applied when installing games.

**Comment by Yelo420** [comment]
Implemented
