### ISSUE TITLE
Add tray icon options to task context menu aswell

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#397]
**Is your feature request related to a problem? Please describe.**
Basically i want these options:
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/8827a845-8709-4575-b986-601934b60150)

here aswell:
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/fd59fc22-1b0b-4e2a-b268-41416d3e72fc)

just like steam etc do:
![image](https://github.com/Phalcode/gamevault-app/assets/22225051/03a03a02-b542-4d81-8abc-dc9d6a4055c1)

Extra Feature:
Bonus points if you implement the "Recent" Tab aswell so it offers to launch the last 5 played games.

**Comment by Yelo420** [comment]
Implemented
![image](https://github.com/Phalcode/gamevault-app/assets/88632464/34b3e0aa-d93c-4504-a95b-28789049ea1a)
Thanks for the bonus points :)
