### ISSUE TITLE
Escape Key does'nt work after opening Game Settings

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#399]
**Describe the bug**
After entering a games settings i cant go back to the library using ESC.

**To Reproduce**
1. Open Library
2. Go to Game
3. Open Game Settings
4. Press ESC to close Settings
5. Press ESC again to close Game (**DOESNT WORK**)

It works after clicking anywhere on the game page after exiting the settings. I think some focus shit is is the root of the problem.

**Expected behavior**
1. Open Library
2. Go to Game
3. Open Game Settings
4. Press ESC to close Settings
5. Press ESC again to close Game

**Comment by Yelo420** [comment]
Same issue with: Open Library -> Open Game settings From Card -> ESC -> F5 (Not working)

Both fixed now
