### ISSUE TITLE
Replace obsolete WebClient and WebRequest with modern HttpClient

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#4]
https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated

**Comment by Alfagun74** [comment]
It is true that if you have several HTTPClients, several WebClients you dispose are faster.
However having a HTTPClient running and reusing it results in much better performace.
Even Microsoft themselves recommend using HttpClient: 

See: https://learn.microsoft.com/en-us/dotnet/api/system.net.webclient?view=net-5.0#remarks
And: https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated#change-description

**Comment by Yelo420** [comment]
As said in Current Architecture.

When frequently repeating create -> run -> dispose in quick succession, the WebClient performs better (also tested on the program itself).

To use the HttpClient effectively, I have to change some stuff in the core. 

But then the title of the issue doesn't do justice to the content.

Maybe rather "Improve Image cache performance", or something like that.
