### ISSUE TITLE
Escape Key does'nt work in Game Settings after remapping a game

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#402]
**Describe the bug**
After remapping a game i cant go back to the game view using ESC.

![image](https://github.com/Phalcode/gamevault-app/assets/22225051/e4279dc6-2b02-481c-8f1d-1d404adc0025)

**To Reproduce**
1. Open Library
2. Go to Game
4. Open Game Settings
5. Remap Game
6. Press ESC to close Settings (**DOESNT WORK**)

It works after clicking anywhere on the game page after exiting the settings. I think some focus shit is is the root of the problem.

**Expected behavior**
1. Open Library
2. Go to Game
4. Open Game Settings
5. Remap Game
6. Press ESC to close Settings

**Comment by Yelo420** [comment]
Same problem with recache, but its fixed now
