### ISSUE TITLE
Ability to change and overwrite the currently selected Installation Procedure

### ISSUE THREAD

**Issue by jakendrick3** [Phalcode/gamevault-app#404]
**Is your feature request related to a problem? Please describe.**
It's a tad frustrating to download an app that is Windows Portable, but that I haven't tagged as such yet on the server, and then get to the install path and have no workaround for just telling it to install the app as a portable app, which leads to me having to delete it from my computer, tag it on the server, then redownload/extract. 

**Describe the solution you'd like**
It'd be nice to have a button in the install phase that just overrides the autodetect and installs the game to the install folder as a portable game. For games that come bundled with redistributables, it's convenient to still have the list of executables in the installer to run those, but once I'm done with those I'd like a button that just moves it to the install folder for me. 

**Describe alternatives you've considered**
While https://github.com/Phalcode/gamevault-backend/issues/148 is being worked on, I think it'd be nice to have a good alternative since a lot of games I manage are portable.

**Comment by Alfagun74** [comment]
Good idea but why does the autotype detection not work for you? I personally rarely tag my games manually.

**Comment by Yelo420** [comment]
Currently, if a game is not tagged, you get the message that Gamevault does not know what to do with the game. How about adding buttons or a dropdown that says: "Game tag could not be recognized -> continue as (Portable)/(Setup)/(etc..)?".

**Comment by jakendrick3** [comment]
Maybe I just get a lot of false positives with mine? Even games not bundled with multiple installers are like this if they have more than one or two .exe files.

**Comment by Alfagun74** [comment]
Please set the log level to debug and index a couple new games, then send me the log, so i can see what causes this.

**Comment by Alfagun74** [comment]
Planned:

- For undetected Games:
  - [ ] Ability to choose and force a specific Installation Procedure (Install as Portable, Install as Windows Setup, Install as Nintendo DS Game, etc.)
- For Falsely Game Types:
  - [ ] Ability to change and overwrite the currently selected Installation Procedure (Install as Portable, Install as Windows Setup, Install as Nintendo DS Game, etc.)

**Comment by Yelo420** [comment]
Implemented
