### ISSUE TITLE
Uninstall Game opening System32 for some reason?

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#405]
I click uninstall and the dialog opens System32 for some reason.

**Comment by Blevins42069** [comment]
[bulk-sponsorships-template.csv](https://github.com/Phalcode/gamevault-app/files/15369206/bulk-sponsorships-template.csv)
[CONTRIBUTING (1).md](https://github.com/Phalcode/gamevault-app/files/15369207/CONTRIBUTING.1.md)
[CONTRIBUTING.md](https://github.com/Phalcode/gamevault-app/files/15369208/CONTRIBUTING.md)
[CODEOWNERS (1).txt](https://github.com/Phalcode/gamevault-app/files/15369209/CODEOWNERS.1.txt)
[CODEOWNERS.txt](https://github.com/Phalcode/gamevault-app/files/15369210/CODEOWNERS.txt)
[available-rules-for-rulesets.md](https://github.com/Phalcode/gamevault-app/files/15369211/available-rules-for-rulesets.md)

**Comment by Yelo420** [comment]
Need more information, cant reproduce so far

**Comment by Yelo420** [comment]
Fixed

**Comment by Alfagun74** [comment]
The issue was that my Root Folder Path is on the Root Folder of my Drive, which lead to a path string concatination issue. Howewer, now we use Path.Combine wherever possible to prevent this.
