### ISSUE TITLE
Add "Create Desktop Shortcut Automatically" Option to Settings

### ISSUE THREAD

**Issue by jakendrick3** [Phalcode/gamevault-app#406]
**Is your feature request related to a problem? Please describe.**
Not really a problem - more like an unknown. I was actually going to suggest adding a create desktop shortcut button when I looked and realized that it exists, it's just hiding under game settings.

**Describe the solution you'd like**
Either an option in settings to create shortcuts for all games automatically, or an option at install to make a shortcut there.

**Comment by Alfagun74** [comment]
Moved into https://github.com/Phalcode/gamevault-app/issues/412
