### ISSUE TITLE
Gamevault crashes when trying to extract games

### ISSUE THREAD

**Issue by casudo** [Phalcode/gamevault-app#407]
**Describe the bug**
Gamevault crashes when trying to extract games. It seems like it was extracted successfully when I open the download path, because the "Extract" folder is filled with the contents of the .zip, but the frontend crashes after ~2 sec when I click the extract button. Therefore, even if it seems like the game extracted, I cannot install it via Gamevault.

**To Reproduce**
1. Go to Downloads
2. Click on "Extract"

**Expected behavior**
The game should be extracted and ready to install via the GUI.

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/c7b51710-1272-4ce8-bc3f-12fa5e2d629c)

**Desktop (please complete the following information):**
- Windows 10

**Comment by casudo** [comment]
**Update:** I've removed the whole game and re-downloaded it. This time I saw the progress bar for extracting and also the "gamevault-metadata" appeared with its contents inside the "Extract" folder. In the end I could install the game successfully.

The only thing that bothers me now that the state of the game in the "Downloads" tab still shows "Extracted" rather than "Installed".
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/85fb48e6-0261-498b-9037-799babf613e0)

**Comment by Yelo420** [comment]
> **Describe the bug** Gamevault crashes when trying to extract games. It seems like it was extracted successfully when I open the download path, because the "Extract" folder is filled with the contents of the .zip, but the frontend crashes after ~2 sec when I click the extract button. Therefore, even if it seems like the game extracted, I cannot install it via Gamevault.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Downloads
> 2. Click on "Extract"
> 
> **Expected behavior** The game should be extracted and ready to install via the GUI.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/55252063/333885780-c7b51710-1272-4ce8-bc3f-12fa5e2d629c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzY2MjIsIm5iZiI6MTcxNjczNjMyMiwicGF0aCI6Ii81NTI1MjA2My8zMzM4ODU3ODAtYzdiNTE3MTAtMTI3Mi00Y2U4LWJjM2YtMTJmYTVlMmQ2MjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDhhYjc5N2Q2ZTkxNmMzZWEzYWY1MjVkNWM4MTA0N2NhNzNhOGE3ZWEwNWM4ZDMyMjEzNjA0ZDZlODgxZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6YDJaXpfzWCbkZHD19D8e0Ng-lBIxnFb0-ZZW0wgc3s)
> 
> **Desktop (please complete the following information):**
> 
> * Windows 10

Can you provide more infos about the crash? Any error message you've got? Maybe you can take a look into the errorlogs. You can find them here:
Github Version:
%USERPROFILE%\AppData\Roaming\GameVault\errorlog
MC Store Version:
%USERPROFILE%\AppData\Local\Packages\Phalcode.174950BD81C41_dymsgn3qpfjxc\LocalCache\Roaming\GameVault\errorlog

Do you have auto extract enabled? Are you able to reproduce this crash? (Because i can't)

**Comment by casudo** [comment]
> Can you provide more infos about the crash? Any error message you've got? Maybe you can take a look into the errorlogs. You can find them here: Github Version: %USERPROFILE%\AppData\Roaming\GameVault\errorlog
I don't have the errorlog file weirdly.

> Do you have auto extract enabled? 
No.

> Are you able to reproduce this crash? (Because i can't)
Since I re-downloaded the games, I cannot reproduce it. Maybe there were some faulty or missing bits.

**Comment by Yelo420** [comment]
I will close the ticket for now. If it occurs again, please reopen it again. Also make a backup of the incorrect data so that I can analyze it in more detail.


> The only thing that bothers me now that the state of the game in the "Downloads" tab still shows "Extracted" rather than "Installed".

This seems to be a bug. Could it be, that the game type is a game with a setup executable?

**Comment by Yelo420** [comment]
I digged a bit around and was actually able to reproduce the error. Should be fixed now.

**Comment by Yelo420** [comment]
> The only thing that bothers me now that the state of the game in the "Downloads" tab still shows "Extracted" rather than "Installed".

Also fixed

**Comment by casudo** [comment]
@Yelo420 Awesome job, thank you for fixing it that fast! May I ask what caused this bug?

**Comment by Yelo420** [comment]
Without going into too much detail, there was a rather harmless data error, which was unfortunately thrown in the progress update event of the 7zip subprocess. This led to a chain of errors that this subprocess also hard crashed the main process. Nothing the global error handler could catch.

**Comment by casudo** [comment]
@Yelo420 It seems like the bug with the wrong state of the game in the downloads persists in v0.10.1.0. 

I've just installed a game which, after installation, correctly showed the "State: Installed" status. After restarting GameVault, its back to "State: Extracted".

**Comment by Yelo420** [comment]
In this case its intentional.

The download card should exist independently and give the user the possibility to edit his “download” even after installation. For example: After a portable game has been installed, the Extract folder no longer exists. So the game is installed, BUT the download is in status downloaded again. The state switch to "Installed" right after installation is just for the userflow.

If you have any ideas for changes, please let us know and we will discuss them internally.

**Comment by casudo** [comment]
> In this case its intentional.
> 
> The download card should exist independently and give the user the possibility to edit his “download” even after installation. For example: After a portable game has been installed, the Extract folder no longer exists. So the game is installed, BUT the download is in status downloaded again. The state switch to "Installed" right after installation is just for the userflow.
> 
> If you have any ideas for changes, please let us know and we will discuss them internally.

Alright, sounds great. Maybe a counter and date displaying next to the downloaded game to inform the user that he/she already installed the game sometime.
