### ISSUE TITLE
Unpaywall URI command to launch Games

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#412]
Unpaywalling the launch endpoint would bring many benefits regarding game launches:

- #393 would not be necessary, as the launch uri would automatically launch gamevault with the current selected Exe and parameters.
- #406 could be implemented.
- In the future emulators and everything else necessary to run a game could be launched this way.

Todos:
- [x] Unpaywall launch URI.
- [x] Make shortcuts link to launch URI.
- [x] Ask if users want a shortcut upon clicking install.

**Comment by Yelo420** [comment]
Implemented
