### ISSUE TITLE
I suggest that the "+" and "-" be reversed for row count in installed game display section.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#418]
I love that this was added!

Might I suggest that the places be reveresed to make it just a little more natural/intuitive? I think it is just a little closer to what the user expects.

![suggestion-after](https://github.com/Phalcode/gamevault-app/assets/25695143/c3310ccf-530b-4965-abbe-4cf85f2cc328)

What do you think?

**Comment by Alfagun74** [comment]
yeah, sure.

 @Yelo420

**Comment by Yelo420** [comment]
yea, sure. 
Implementded.
