### ISSUE TITLE
Titles with colon do not appear in client

### ISSUE THREAD

**Issue by The1CABAL** [Phalcode/gamevault-app#420]
**Describe the bug**
After including a game to the backend (running on Debian 10) which contains a ":" in the title, such as "Hardspace: Shipbreaker (2020) (Build 10407420).zip" the title does not appear in the client (running on Windows 11)

**To Reproduce**
1. Add a game with a title like "Hardspace: Shipbreaker" to the games directory of the backend app running on Debian 10
2. Search the game in the Server Games list on the Windows 11 client side. (Actual Result: Game does not appear)
3. Restart windows client as sanity check and observe Server Games list (Actual Result: Game does not appear)
4. As a final sanity check rename the zip file to omit the special character (":") and search the Server Games list. 
5. Observe the game appear with no box art

**Expected behavior**
The backend and the client should both be able to parse special characters in game file names to minimize user intervention in the upload process. 

**Desktop (please complete the following information):**
 - Backend OS: Debian 10 5.10.0-0.deb10.16-amd64
 - Client OS: Windows 11 Home 23H2

**Additional context**
I am unsure which repo to report this to, please let me know if this has been reported and closed already and/or if this is in the wrong repo.

**Comment by Alfagun74** [comment]
Greetings, colons are illegal characters in the Windows file system and have to be replaced with a dash.

For more details see: ​https://gamevau.lt/docs/server-docs/structure#naming-convention-for-games

**Comment by The1CABAL** [comment]
> Greetings, colons are illegal characters in the Windows file system and have to be replaced with a dash.
> 
> For more details see: ​https://gamevau.lt/docs/server-docs/structure#naming-convention-for-games

Thanks for the correction. I had a feeling it would be something like this.
