### ISSUE TITLE
Filter by Completion Status

### ISSUE THREAD

**Issue by Bovive** [Phalcode/gamevault-app#426]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be nice to be able to filter the games by completion status (Unplayed, Playing, Completed, etc). Right now each game can be marked as one of those categories but without being able to filter them it isn't terribly useful. It would be nice to see only games marked as Unplayed for example.

**Comment by Yelo420** [comment]
Implemented on clientside
