### ISSUE TITLE
App is asking for uninstall exe for portable games.

### ISSUE THREAD

**Issue by Snussune** [Phalcode/gamevault-app#435]
**Describe the bug**
When i install a portable game the app sometimes thinks it's an installable version, when i set it to forced portable the app should not expect an uninstall exe when uninstalling the game.

**To Reproduce**
1. Install a portable game that requires you to set it to force it as portable.
2. Click "Uninstall game"

**Expected behavior**
When clicking "Uninstall game" the program should check if the game was set to forced portable, if it was it should simply delete the game directory instead of asking for the uninstall exe file.

**Comment by Alfagun74** [comment]
Very interesting find. We will see if we can reproduce this and come back to you sooner or later.

**Comment by Yelo420** [comment]
The forced install type is not remembered right now. We will discuss how we will handle this in the future.

**Comment by Alfagun74** [comment]
We need to store the forced installation type in the installation metadata file and make the uninstaller react to it.

**Comment by Yelo420** [comment]
Implemented and available in the next version
