### ISSUE TITLE
Application name is blank in the taskbar

### ISSUE THREAD

**Issue by Snussune** [Phalcode/gamevault-app#444]
The application has a blank name in the windows taskbar when the taskbar setting "Combine taskbar buttons and hide labels" is set to "Never"

See the following screenshots for an explanation:

How it looks compared to other applications in the taskbar. Here it should say "Gamevault" next to the icon.

![image](https://github.com/user-attachments/assets/3685fd78-1b5d-4cfd-a5ba-493c57fba31e)

The setting in windows to reproduce the bug:

![image](https://github.com/user-attachments/assets/5489224b-e9b8-41ef-9940-6f427f356467)

**Comment by Alfagun74** [comment]
Thanks for reporting this. We have been able to reproduce the bug and will fix it.

**Comment by Yelo420** [comment]
Fixed in the next version
