### ISSUE TITLE
[Suggestion] Make the Description Metadata field editable, not just rewritable

### ISSUE THREAD

**Issue by Kappawaii** [Phalcode/gamevault-app#445]
![image](https://github.com/user-attachments/assets/47ab08e2-d7cb-4362-8a78-72e34ed082bd)

For example, here I have a description provided by IGDB with 2x the same paragraph, and I have to rewrite everything or find it directly online and repaste it, instead of just editing it. It would imo be much easier to use if you could edit the text. If people wanna rewrite it completely, they can just hit Ctrl-A Suppr instead.

**Comment by Alfagun74** [comment]
You don't need to rewrite everything, luckily! 😄 You can simply use this button here to copy the currently applied metadata for editing.

![image](https://github.com/user-attachments/assets/b5aaf9fa-fd12-426a-af2f-b8b1b7ac2ca3)

We may look into improving these edit form to be more intuitive in the future.
