### ISSUE TITLE
How can i update version of the GameVault? What do i have to do?

### ISSUE THREAD

**Issue by Sagjane** [Phalcode/gamevault-app#446]
How can i update version of the GameVault? What do i have to do?

**Comment by Alfagun74** [comment]
For the server, please check out the [migration guide](https://github.com/Phalcode/gamevault-backend/releases/tag/13.0.0) in the changelog.

For the client, if you installed it from Microsoft Store it will prompt you to update automatically, if you installed it through GitHub it will prompt you to install it manually by downloading the latest version [from GitHub](https://github.com/Phalcode/gamevault-app/releases/tag/1.12.5.0)
