### ISSUE TITLE
News icon always shows exclamation point on startup

### ISSUE THREAD

**Issue by kjack9** [Phalcode/gamevault-app#450]
**Describe the bug**
The News icon in the bottom left bar always shows the "new news" exclamation point on startup, even if there is nothing new. The exclamation point goes away after clicking the icon, but re-appears the next time the app is restarted.

**To Reproduce**
1. Close app
2. Open app
3. Observe exclamation point
4. Click news icon and observe exclamation point disappearing
5. Close app
6. Open app
7. Observe exclamation point

**Expected behavior**
Exclamation point should only show if there is new news

**Screenshots**
![image](https://github.com/user-attachments/assets/96595ae9-221b-407d-be02-0c2e9612617a)

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
N/A

**Comment by Alfagun74** [comment]
Are you absolutely sure nothing changed?

The exclamation mark should only be visible if either GameVault News or Server News have changed.

@Yelo420 how do we the save news state?

**Comment by Yelo420** [comment]
That’s strange. The news state is saved by creating a hash of the 'GV News' and 'Server News' and comparing it with the previous one.
@kjack9, if you’re sure that nothing has really changed, could you take a look at the server message and let me know if there are any special characters, or if it’s empty? I’m looking for any specific cases that could be causing this.

**Comment by kjack9** [comment]
> That’s strange. The news state is saved by creating a hash of the 'GV News' and 'Server News' and comparing it with the previous one. @kjack9, if you’re sure that nothing has really changed, could you take a look at the server message and let me know if there are any special characters, or if it’s empty? I’m looking for any specific cases that could be causing this.

100% sure since I don't have a server message set. The "GameVault News" tab shows the initial message -- "Welcome to the new GameVault news section!". My "Server News" is blank as I haven't set it up with anything.

Also note that there is sometimes a delay before the exclamation point shows up again -- a few hours ago I closed and re-opened, and it wasn't there. Checked again just now, and it's back.

**Comment by Yelo420** [comment]
@kjack9 Is this still a Problem?

**Comment by Yelo420** [comment]
If this is still a problem, please open a new ticket
