### ISSUE TITLE
My game wont download, it keeps crashing down everytime i try to download it.

### ISSUE THREAD

**Issue by Sagjane** [Phalcode/gamevault-app#453]
![Snímka obrazovky 2024-11-01 214650](https://github.com/user-attachments/assets/03a8ff61-8acf-4917-842a-71819f90a7e3)
![Snímka obrazovky 2024-11-01 214147](https://github.com/user-attachments/assets/7e0f14dc-67bc-4152-bf97-4c24759ede1d)

**Comment by Alfagun74** [comment]
How long does it download until It crashes?

Btw there's a reason we provide a template for bugs to fill out. Not using it makes it pretty hard for us to find your problem.

I presume it's your reverse proxy, that has a limit set on how long a request can run. Downloading this game takes longer and thus your proxy kills the connection. It can be nginx, cloudflare, traefik, caddy or whatever you use that is in-between you and the gamevault server.

It can also be a max body size issue.
Check your reverse proxy configuration.

**Comment by Yelo420** [comment]
@Sagjane Does the problem persist?

**Comment by Yelo420** [comment]
Seems not. But if it will pop up again, please open a new Ticket
