### ISSUE TITLE
IO Error on download loops endlessly

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#456]
**Describe the bug**  
The GV client can enter a state where it repeatedly attempts to download a file without having the necessary permissions to write it, resulting in excessive API calls and potential performance issues.

**To Reproduce**  
1. Start a download of a large file (e.g., 77GB) using the GV client.
2. Ensure that the file system has a write permission issue (e.g., file lock or insufficient storage).
3. Observe the client as it attempts to download the file.
4. Notice that the client repeatedly hits the API endpoint multiple times a minute without successfully writing the file.

**Expected behavior**  
The client should stop attempting to download the file when it encounters a write permission issue or file lock, rather than continuously retrying and causing unnecessary API calls.

**Additional context**  
Suggestions:
- If you run into a IO issue on the client side, stop. The includes but is not limited to access issues and storage space limitations. Continuing to try is a waste of effort, and will simply cause the same issue to happen over and over.
- Get a file lock before you start downloading. No reason to even reach out to the API if you're not going to be able to do anything with the data when you download it.
- Surface the error is a much more obvious way. In this case, I knew there was a problem because of my discord alerts. But if I didn't have that, neither myself nor the end user would have known anything was awry. It's quite likely the error would have recurred multiple times a minute over many days.

**Comment by Yelo420** [comment]
So would a targeted query for repeatedly IO errors be the solution here? I said “repeatedly” because it can happen that the file is only blocked for a short time for various reasons.

**Comment by KairuByte** [comment]
That would indeed handle the issue. Maybe a max retry count, or based on what the error is. For instance, if the error is that there is not enough disk space, it's not likely going to solve itself. But it wouldn't hurt to try again.

It would also be useful to not attempt to download unless you get a file lock on subsequent attempts. Though admittedly the main reason I care about this aspect is because I am using a free tier edge worker on cloudflare, which is limited to a certain number of invocations per month.

There's also a high potential that the lock in this particular case was caused by GV itself, as the PC was left to it's own devices once the download was started, and it got about 80% of the way through before it ran into this perpetual file lock issue. Restarting GV did remove the file lock and allow the download to start as expected.

**Comment by Yelo420** [comment]
Fixed by adding bleedoff to the retry timer tick rate
