### ISSUE TITLE
Add games to steam vai non steam game interface

### ISSUE THREAD

**Issue by TConnor2003** [Phalcode/gamevault-app#458]
**Is your feature request related to a problem? Please describe.**
Im thinking of installing this app on my server as i have a few games from gog that i tend to install and add to steam using the non steam game interface then i have to go to steamgrid to get the custom artwork

**Describe the solution you'd like**
An option in the client app to automatically add downloaded games to the steam ui and add metadata

**Describe alternatives you've considered**
My current solution is manyallu adding the game and artwork to steam

**Comment by Alfagun74** [comment]
dupe of https://github.com/Phalcode/gamevault-app/issues/443
